{.passL:"-lTKFillet".}
{.passC:"-I/usr/include/opencascade/" .}

import blendfunc
import blendfunc_chamfer
import blendfunc_chamfinv
import blendfunc_chasym
import blendfunc_chasyminv
import blendfunc_constrad
import blendfunc_constradinv
import blendfunc_constthroat
import blendfunc_constthroatinv
import blendfunc_constthroatwithpenetration
import blendfunc_constthroatwithpenetrationinv
import blendfunc_corde
import blendfunc_cscircular
import blendfunc_csconstrad
import blendfunc_evolrad
import blendfunc_evolradinv
import blendfunc_genchamfer
import blendfunc_genchamfinv
import blendfunc_ruled
import blendfunc_ruledinv
import blendfunc_sectionshape
import blendfunc_tensor

export blendfunc, blendfunc_chamfer, blendfunc_chamfinv, blendfunc_chasym, blendfunc_chasyminv, blendfunc_constrad, blendfunc_constradinv, blendfunc_constthroat, blendfunc_constthroatinv, blendfunc_constthroatwithpenetration, blendfunc_constthroatwithpenetrationinv, blendfunc_corde, blendfunc_cscircular, blendfunc_csconstrad, blendfunc_evolrad, blendfunc_evolradinv, blendfunc_genchamfer, blendfunc_genchamfinv, blendfunc_ruled, blendfunc_ruledinv, blendfunc_sectionshape, blendfunc_tensor
