/* Generated by Nim Compiler v1.6.10 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   g++ -c -std=gnu++14 -funsigned-char  -w -fmax-errors=3 -fpermissive -I/usr/include/opencascade/ -I/usr/import/opencascade/ -O3 -fno-strict-aliasing -fno-ident   -I/home/jose/.choosenim/toolchains/nim-1.6.10/lib -I/home/jose/src/nimlang/occt.nim/examples/api -o /home/jose/src/nimlang/occt.nim/examples/api/borrame/@m..@s..@ssrc@slib@stkoffset@stkoffset.nim.cpp.o /home/jose/src/nimlang/occt.nim/examples/api/borrame/@m..@s..@ssrc@slib@stkoffset@stkoffset.nim.cpp */
#define NIM_INTBITS 64

#include "nimbase.h"
#include "TopoDS_Shape.hxx"
#include "NCollection_List.hxx"
#include "NCollection_BaseList.hxx"
#include "BRepOffset_Mode.hxx"
#include "GeomAbs_JoinType.hxx"
#include "Message_ProgressRange.hxx"
#include "BRepOffsetAPI_MakeThickSolid.hxx"
#include "BRepOffsetAPI_MakeOffsetShape.hxx"
#include "BRepBuilderAPI_MakeShape.hxx"
#include "BRepBuilderAPI_Command.hxx"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef NCollection_List<TopoDS_Shape> TY__GIqsjlKJHsTq0jbUI9bnu9aw;
N_LIB_PRIVATE N_NIMCALL(TopoDS_Shape, makeThickSolidByJoin__OOZOOZsrcZlibZtkoffsetZtkoffset_3)(TopoDS_Shape S, TY__GIqsjlKJHsTq0jbUI9bnu9aw ClosingFaces, NF Offset_0, NF Tol, BRepOffset_Mode Mode_0, NIM_BOOL Intersection, NIM_BOOL SelfInter, GeomAbs_JoinType Join, NIM_BOOL RemoveIntEdges, Message_ProgressRange theRange) {
	TopoDS_Shape result;
	BRepOffsetAPI_MakeThickSolid aSolidMaker;
{	aSolidMaker.MakeThickSolidByJoin(S, ClosingFaces, ((float) (Offset_0)), ((float) (Tol)), Mode_0, Intersection, SelfInter, Join, RemoveIntEdges, theRange);
	result = aSolidMaker.Shape();
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
