/* Generated by Nim Compiler v1.6.10 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   g++ -c -std=gnu++14 -funsigned-char  -w -fmax-errors=3 -fpermissive -I/usr/include/opencascade/ -I/usr/import/opencascade/ -O3 -fno-strict-aliasing -fno-ident   -I/home/jose/.choosenim/toolchains/nim-1.6.10/lib -I/home/jose/src/nimlang/occt.nim/examples/api -o /home/jose/src/nimlang/occt.nim/examples/api/borrame/@m..@s..@ssrc@swrapper@stkbrep@stopods@stopods_types.nim.cpp.o /home/jose/src/nimlang/occt.nim/examples/api/borrame/@m..@s..@ssrc@swrapper@stkbrep@stopods@stopods_types.nim.cpp */
#define NIM_INTBITS 64

#include "nimbase.h"
#include "TopoDS_Shape.hxx"
#include "TopoDS_Edge.hxx"
#include "TopoDS_Wire.hxx"
#include "TopoDS_Face.hxx"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
struct TNimType;
struct TNimNode;
typedef NU8 tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc__ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
NI align;
tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc__ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
N_LIB_PRIVATE TNimType NTItopods95shape__EbhlUdygTvfLelaziGdVeQ_;
N_LIB_PRIVATE TNimType NTItopods95edge__jOPcFChOFG9cvA9a2u619aaSA_;
N_LIB_PRIVATE TNimType NTItopods95wire__iXlfJUv20QZLaQkRrdvITg_;
N_LIB_PRIVATE TNimType NTItopods95face__eb9aQZydUaK6E9b2LeoS4WBw_;
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatssrcatswrapperatstkbrepatstopodsatstopods_typesdotnim_DatInit000)(void) {
static TNimNode TM__9ab38sbchvasXCVCKJy8YZA_0[4];
NTItopods95shape__EbhlUdygTvfLelaziGdVeQ_.size = sizeof(TopoDS_Shape);
NTItopods95shape__EbhlUdygTvfLelaziGdVeQ_.align = NIM_ALIGNOF(TopoDS_Shape);
NTItopods95shape__EbhlUdygTvfLelaziGdVeQ_.kind = 18;
NTItopods95shape__EbhlUdygTvfLelaziGdVeQ_.base = 0;
NTItopods95shape__EbhlUdygTvfLelaziGdVeQ_.flags = 1;
NTItopods95shape__EbhlUdygTvfLelaziGdVeQ_.node = &TM__9ab38sbchvasXCVCKJy8YZA_0[0];
NTItopods95edge__jOPcFChOFG9cvA9a2u619aaSA_.size = sizeof(TopoDS_Edge);
NTItopods95edge__jOPcFChOFG9cvA9a2u619aaSA_.align = NIM_ALIGNOF(TopoDS_Edge);
NTItopods95edge__jOPcFChOFG9cvA9a2u619aaSA_.kind = 18;
NTItopods95edge__jOPcFChOFG9cvA9a2u619aaSA_.base = (&NTItopods95shape__EbhlUdygTvfLelaziGdVeQ_);
NTItopods95edge__jOPcFChOFG9cvA9a2u619aaSA_.flags = 1;
NTItopods95edge__jOPcFChOFG9cvA9a2u619aaSA_.node = &TM__9ab38sbchvasXCVCKJy8YZA_0[1];
NTItopods95wire__iXlfJUv20QZLaQkRrdvITg_.size = sizeof(TopoDS_Wire);
NTItopods95wire__iXlfJUv20QZLaQkRrdvITg_.align = NIM_ALIGNOF(TopoDS_Wire);
NTItopods95wire__iXlfJUv20QZLaQkRrdvITg_.kind = 18;
NTItopods95wire__iXlfJUv20QZLaQkRrdvITg_.base = (&NTItopods95shape__EbhlUdygTvfLelaziGdVeQ_);
NTItopods95wire__iXlfJUv20QZLaQkRrdvITg_.flags = 1;
NTItopods95wire__iXlfJUv20QZLaQkRrdvITg_.node = &TM__9ab38sbchvasXCVCKJy8YZA_0[2];
NTItopods95face__eb9aQZydUaK6E9b2LeoS4WBw_.size = sizeof(TopoDS_Face);
NTItopods95face__eb9aQZydUaK6E9b2LeoS4WBw_.align = NIM_ALIGNOF(TopoDS_Face);
NTItopods95face__eb9aQZydUaK6E9b2LeoS4WBw_.kind = 18;
NTItopods95face__eb9aQZydUaK6E9b2LeoS4WBw_.base = (&NTItopods95shape__EbhlUdygTvfLelaziGdVeQ_);
NTItopods95face__eb9aQZydUaK6E9b2LeoS4WBw_.flags = 1;
NTItopods95face__eb9aQZydUaK6E9b2LeoS4WBw_.node = &TM__9ab38sbchvasXCVCKJy8YZA_0[3];
}

