/* Generated by Nim Compiler v1.6.10 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   g++ -c -std=gnu++14 -funsigned-char  -w -fmax-errors=3 -fpermissive -I/usr/include/opencascade/ -I/usr/import/opencascade/ -O3 -fno-strict-aliasing -fno-ident   -I/home/jose/.choosenim/toolchains/nim-1.6.10/lib -I/home/jose/src/nimlang/occt.nim/examples/api -o /home/jose/src/nimlang/occt.nim/examples/api/borrame/@m..@s..@ssrc@slib@ssketcher@ssketcher2d.nim.cpp.o /home/jose/src/nimlang/occt.nim/examples/api/borrame/@m..@s..@ssrc@slib@ssketcher@ssketcher2d.nim.cpp */
#define NIM_INTBITS 64

#include "nimbase.h"
#include "TopoDS_Shape.hxx"
#include "BRepFilletAPI_MakeFillet.hxx"
#include "BRepFilletAPI_LocalOperation.hxx"
#include "BRepBuilderAPI_MakeShape.hxx"
#include "BRepBuilderAPI_Command.hxx"
#include "ChFi3d_FilletShape.hxx"
#include "TopoDS_Edge.hxx"
#include "TopExp_Explorer.hxx"
#include "TopAbs_ShapeEnum.hxx"
#include "TopoDS.hxx"
#include "TopoDS_Wire.hxx"
#include "TopoDS_Face.hxx"
#include "BRepBuilderAPI_MakeFace.hxx"
#include "gp_Vec.hxx"
#include "BRepPrimAPI_MakePrism.hxx"
#include "BRepBuilderAPI_MakeWire.hxx"
#include "Geom2d_VectorWithMagnitude.hxx"
#include "Geom2d_Vector.hxx"
#include "Geom2d_Geometry.hxx"
#include "Standard_Transient.hxx"
#include "gp_Pnt2d.hxx"
#include "Geom2d_Transformation.hxx"
#include "gp_Ax2d.hxx"
#include "gp_Dir2d.hxx"
#include "gp_Trsf.hxx"
#include "BRepBuilderAPI_Transform.hxx"
#include "BRepBuilderAPI_ModifyShape.hxx"
#include "BRepLib.hxx"
#include <string.h>
#include "BRepBuilderAPI_MakeEdge2d.hxx"
#include "Standard_Handle.hxx"
#include "Geom2d_TrimmedCurve.hxx"
#include "Geom2d_BoundedCurve.hxx"
#include "Geom2d_Curve.hxx"
#include "GCE2d_MakeArcOfCircle.hxx"
#include "gp_Pnt.hxx"
#include "gp_Dir.hxx"
#include "gp_Ax2.hxx"
#include "BRepPrimAPI_MakeCylinder.hxx"
#include "NCollection_List.hxx"
#include "NCollection_BaseList.hxx"
#include "BRepOffset_Mode.hxx"
#include "GeomAbs_JoinType.hxx"
#include "Message_ProgressRange.hxx"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
struct RootObj;
struct TNimType;
struct TNimNode;
struct tyObject_Sketch2dObj__69bjq5HIgQ8lj6TeGoMpO9cQ;
struct tySequence__f9aB3gxGPxALrM2IRe7gyQg;
struct tySequence__GdhZuuACwFC00AwlRIU9b4A;
struct tySequence__0fMAnTwz5AxtkqIdipBt4w;
struct tySequence__uglp2GtOV9bH7gMNc6PppLg;
struct NimStringDesc;
struct TGenericSeq;
struct tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g;
struct tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w;
struct tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ;
struct tyObject_GcStack__7fytPA5bBsob6See21YMRA;
struct tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg;
struct tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ;
struct tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg;
struct tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw;
struct tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA;
struct tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw;
struct tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw;
struct tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg;
struct tyTuple__ujsjpB2O9cjj3uDHsXbnSzg;
struct tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg;
struct tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ;
struct tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg;
struct tySequence__p3ejDZUwgffAWrdMTTu9c7Q;
typedef NU8 tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc__ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
NI align;
tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc__ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
struct RootObj {
TNimType* m_type;
};
struct tyObject_Sketch2dObj__69bjq5HIgQ8lj6TeGoMpO9cQ {
tySequence__f9aB3gxGPxALrM2IRe7gyQg* points;
tySequence__GdhZuuACwFC00AwlRIU9b4A* segments;
tySequence__0fMAnTwz5AxtkqIdipBt4w* wires;
tySequence__uglp2GtOV9bH7gMNc6PppLg* shapes;
};
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc : public TGenericSeq {
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NF tyArray__Tgy9b6R4KdSrcLohzVAUl8w[2];
typedef NU8 tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack__7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ* tyArray__SPr7N6UKfuF549bNPiUvSRw[256];
typedef NU32 tyArray__BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg* tyArray__N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray__N1u1nqOgmuJN9cSZrnMHgOQ tyArray__B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw* tyArray__lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA {
tyArray__lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* tyArray__0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw {
tyArray__0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple__ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple__ujsjpB2O9cjj3uDHsXbnSzg tyArray__LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray__LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray__SPr7N6UKfuF549bNPiUvSRw freeSmallChunks;
NU32 flBitmap;
tyArray__BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray__B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack__7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
NI zctThreshold;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
typedef opencascade::handle<Geom2d_TrimmedCurve> TY__gr9cHpXf2T9bJg9bMQ9cd8A9cDQ;
typedef NCollection_List<TopoDS_Shape> TY__GIqsjlKJHsTq0jbUI9bnu9aw;
struct tySequence__f9aB3gxGPxALrM2IRe7gyQg : TGenericSeq {
  tyArray__Tgy9b6R4KdSrcLohzVAUl8w data[SEQ_DECL_SIZE];
};
struct tySequence__GdhZuuACwFC00AwlRIU9b4A : TGenericSeq {
  TopoDS_Edge data[SEQ_DECL_SIZE];
};
struct tySequence__0fMAnTwz5AxtkqIdipBt4w : TGenericSeq {
  TopoDS_Wire data[SEQ_DECL_SIZE];
};
struct tySequence__uglp2GtOV9bH7gMNc6PppLg : TGenericSeq {
  TopoDS_Shape data[SEQ_DECL_SIZE];
};
struct tySequence__p3ejDZUwgffAWrdMTTu9c7Q : TGenericSeq {
  TopoDS_Face data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i, NI n);
N_LIB_PRIVATE N_NIMCALL(void, ampeq___OOZOOZsrcZlibZtopologyZwire_26)(BRepBuilderAPI_MakeWire& wire, TopoDS_Edge edge);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__systemZassertions_56)(NimStringDesc* msg);
N_LIB_PRIVATE N_NIMCALL(gp_Pnt2d, pnt2d__OOZOOZsrcZlibZsketcherZsketcher50d_34)(tyArray__Tgy9b6R4KdSrcLohzVAUl8w p);
N_LIB_PRIVATE N_NIMCALL(NF, x__OOZOOZsrcZlibZsketcherZsketcher50d_20)(tyArray__Tgy9b6R4KdSrcLohzVAUl8w obj);
N_LIB_PRIVATE N_NIMCALL(NF, y__OOZOOZsrcZlibZsketcherZsketcher50d_23)(tyArray__Tgy9b6R4KdSrcLohzVAUl8w obj);
N_LIB_PRIVATE N_NIMCALL(BRepBuilderAPI_MakeWire, amp___OOZOOZsrcZlibZtopologyZwire_49)(TopoDS_Wire w1, TopoDS_Wire w2);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size);
N_LIB_PRIVATE N_NIMCALL(void, yeq___sketcher50d954849_66)(NF* obj, NF val);
N_LIB_PRIVATE N_NIMCALL(TGenericSeq*, incrSeqV3)(TGenericSeq* s, TNimType* typ);
static N_NIMCALL(void, Marker_tySequence__f9aB3gxGPxALrM2IRe7gyQg)(void* p, NI op);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef__system_5317)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(NI, pluspercent___system_696)(NI x, NI y);
static N_INLINE(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell__system_5279)(void* usr);
static N_INLINE(NI, minuspercent___system_716)(NI x, NI y);
static N_INLINE(void, decRef__system_5324)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(NIM_BOOL, ltpercent___system_1005)(NI x, NI y);
static N_INLINE(void, rtlAddZCT__system_5322)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT__system_5273)(tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w& s, tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_NIMCALL(void, Marker_tySequence__GdhZuuACwFC00AwlRIU9b4A)(void* p, NI op);
N_LIB_PRIVATE N_NIMCALL(float, toCfloat__sketcher50d954849_115)(NI val);
N_LIB_PRIVATE N_NIMCALL(tyObject_Sketch2dObj__69bjq5HIgQ8lj6TeGoMpO9cQ*, new__sketcher50d954849_12)(void);
static N_NIMCALL(void, Marker_tySequence__0fMAnTwz5AxtkqIdipBt4w)(void* p, NI op);
static N_NIMCALL(void, Marker_tySequence__uglp2GtOV9bH7gMNc6PppLg)(void* p, NI op);
N_LIB_PRIVATE N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tyRef__UPfoI3fQ9ao79bAcCuk9abq1w)(void* p, NI op);
N_LIB_PRIVATE N_NIMCALL(tySequence__p3ejDZUwgffAWrdMTTu9c7Q*, newSeq__sketcher50d954849_405)(NI len);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i, NI64 a, NI64 b);
N_LIB_PRIVATE N_NIMCALL(TopoDS_Shape, makeThickSolidByJoin__OOZOOZsrcZlibZtkoffsetZtkoffset_3)(TopoDS_Shape S, TY__GIqsjlKJHsTq0jbUI9bnu9aw ClosingFaces, NF Offset_0, NF Tol, BRepOffset_Mode Mode_0, NIM_BOOL Intersection, NIM_BOOL SelfInter, GeomAbs_JoinType Join, NIM_BOOL RemoveIntEdges, Message_ProgressRange theRange);
N_LIB_PRIVATE N_NIMCALL(TY__GIqsjlKJHsTq0jbUI9bnu9aw, toTopTools_ListOfShape__sketcher50d954849_427)(tySequence__p3ejDZUwgffAWrdMTTu9c7Q* shapes);
STRING_LITERAL(TM__wo5SM9aq6i8S8F5tc6S9bIHA_3, "iterators.nim(240, 11) `len(a) == L` the length of the seq changed while iterating over it", 90);
extern TNimType NTIfloat__w9bl9a1ul9ctRJWiMl9cNnIMvg_;
N_LIB_PRIVATE TNimType NTIpoint50dobj__Tgy9b6R4KdSrcLohzVAUl8w_;
N_LIB_PRIVATE TNimType NTIseqLpoint50dobjT__f9aB3gxGPxALrM2IRe7gyQg_;
extern TNimType NTItopods95edge__jOPcFChOFG9cvA9a2u619aaSA_;
N_LIB_PRIVATE TNimType NTIseqLtopods95edgeT__GdhZuuACwFC00AwlRIU9b4A_;
N_LIB_PRIVATE TNimType NTIsketch50dobj__69bjq5HIgQ8lj6TeGoMpO9cQ_;
extern TNimType NTItopods95wire__iXlfJUv20QZLaQkRrdvITg_;
N_LIB_PRIVATE TNimType NTIseqLtopods95wireT__0fMAnTwz5AxtkqIdipBt4w_;
extern TNimType NTItopods95shape__EbhlUdygTvfLelaziGdVeQ_;
N_LIB_PRIVATE TNimType NTIseqLtopods95shapeT__uglp2GtOV9bH7gMNc6PppLg_;
N_LIB_PRIVATE TNimType NTIsketch50dref__UPfoI3fQ9ao79bAcCuk9abq1w_;
extern tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ gch__system_5226;
N_LIB_PRIVATE N_NIMCALL(TopoDS_Shape, fillet__sketcher50d954849_178)(TopoDS_Shape aBody, NF radius) {
	TopoDS_Shape result;
{	BRepFilletAPI_MakeFillet mkFillet(aBody, ((ChFi3d_FilletShape) 0));
	{
		TopoDS_Edge anEdge;
		TopExp_Explorer anExplorer(aBody, ((TopAbs_ShapeEnum) 6), ((TopAbs_ShapeEnum) 8));
		{
			while (1) {
				NIM_BOOL T4_ = anExplorer.More();
				if (!T4_) goto LA3;
				anEdge = TopoDS::Edge(anExplorer.Current());
				mkFillet.Add(((float) (radius)), anEdge);
				anExplorer.Next();
			} LA3: ;
		}
	}
	result = mkFillet.Shape();
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(TopoDS_Shape, extrude__sketcher50d954849_144)(TopoDS_Wire aWire, NF height) {
	TopoDS_Shape result;
{	TopoDS_Face aFace = BRepBuilderAPI_MakeFace(aWire, NIM_FALSE).Face();
	gp_Vec aPrismVec(0.0f, 0.0f, ((float) (height)));
	result = BRepPrimAPI_MakePrism(aFace, aPrismVec, NIM_FALSE, NIM_TRUE).BRepBuilderAPI_MakeShape::operator TopoDS_Shape();
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NF, x__OOZOOZsrcZlibZsketcherZsketcher50d_20)(tyArray__Tgy9b6R4KdSrcLohzVAUl8w obj) {
	NF result;
	result = (NF)0;
	result = obj[(((NI) 0))- 0];
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NF, y__OOZOOZsrcZlibZsketcherZsketcher50d_23)(tyArray__Tgy9b6R4KdSrcLohzVAUl8w obj) {
	NF result;
	result = (NF)0;
	result = obj[(((NI) 1))- 0];
	return result;
}
N_LIB_PRIVATE N_NIMCALL(gp_Pnt2d, pnt2d__OOZOOZsrcZlibZsketcherZsketcher50d_34)(tyArray__Tgy9b6R4KdSrcLohzVAUl8w p) {
	gp_Pnt2d result;
	NF T1_ = x__OOZOOZsrcZlibZsketcherZsketcher50d_20(p);
	NF T2_ = y__OOZOOZsrcZlibZsketcherZsketcher50d_23(p);
	result = gp_Pnt2d(((float) (T1_)), ((float) (T2_)));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(TopoDS_Wire, closeWithMirror__OOZOOZsrcZlibZsketcherZsketcher50d_87)(tyObject_Sketch2dObj__69bjq5HIgQ8lj6TeGoMpO9cQ* skt) {
	TopoDS_Wire result;
	NI T11_;
	NIM_BOOL T15_;
{	BRepBuilderAPI_MakeWire w;
	{
		TopoDS_Edge* s;
		NI T2_;
		s = (TopoDS_Edge*)0;
		NI i = ((NI) 0);
		T2_ = ((*skt).segments ? (*skt).segments->len : 0);
		NI L = T2_;
		{
			while (1) {
				NI TM__wo5SM9aq6i8S8F5tc6S9bIHA_2;
				if (!(i < L)) goto LA4;
				if (i < 0 || i >= ((*skt).segments ? (*skt).segments->len : 0)){ raiseIndexError2(i,((*skt).segments ? (*skt).segments->len : 0)-1); }
				s = (&(*skt).segments->data[i]);
				ampeq___OOZOOZsrcZlibZtopologyZwire_26(w, TopoDS::Edge((*s)));
				if (nimAddInt(i, ((NI) 1), &TM__wo5SM9aq6i8S8F5tc6S9bIHA_2)) { raiseOverflow(); };
				i = (NI)(TM__wo5SM9aq6i8S8F5tc6S9bIHA_2);
				{
					NI T7_;
					T7_ = ((*skt).segments ? (*skt).segments->len : 0);
					if (!!((T7_ == L))) goto LA8_;
{					failedAssertImpl__systemZassertions_56(((NimStringDesc*) &TM__wo5SM9aq6i8S8F5tc6S9bIHA_3));
}				}
				LA8_: ;
			} LA4: ;
		}
	}
	if (((NI) 0) < 0 || ((NI) 0) >= ((*skt).points ? (*skt).points->len : 0)){ raiseIndexError2(((NI) 0),((*skt).points ? (*skt).points->len : 0)-1); }
	gp_Pnt2d T10_ = pnt2d__OOZOOZsrcZlibZsketcherZsketcher50d_34((*skt).points->data[((NI) 0)]);
	T11_ = (((*skt).points ? (*skt).points->len : 0)-1);
	if (T11_ < 0 || T11_ >= ((*skt).points ? (*skt).points->len : 0)){ raiseIndexError2(T11_,((*skt).points ? (*skt).points->len : 0)-1); }
	gp_Pnt2d T12_ = pnt2d__OOZOOZsrcZlibZsketcherZsketcher50d_34((*skt).points->data[T11_]);
	Geom2d_VectorWithMagnitude v(T10_, T12_);
	v.Normalize();
	Geom2d_Transformation aTrsf;
	if (((NI) 0) < 0 || ((NI) 0) >= ((*skt).points ? (*skt).points->len : 0)){ raiseIndexError2(((NI) 0),((*skt).points ? (*skt).points->len : 0)-1); }
	gp_Pnt2d T13_ = pnt2d__OOZOOZsrcZlibZsketcherZsketcher50d_34((*skt).points->data[((NI) 0)]);
	gp_Ax2d ax(T13_, gp_Dir2d(v.X(), v.Y()));
	aTrsf.SetMirror(ax);
	gp_Trsf trf(aTrsf.Trsf2d());
	BRepBuilderAPI_Transform aBRepTrsf(w.Shape(), trf, NIM_FALSE);
	TopoDS_Wire aMirroredWire = TopoDS::Wire(aBRepTrsf.BRepBuilderAPI_MakeShape::operator TopoDS_Shape());
	BRepBuilderAPI_MakeWire T14_ = amp___OOZOOZsrcZlibZtopologyZwire_49(w.BRepBuilderAPI_MakeWire::operator TopoDS_Wire(), aMirroredWire);
	BRepBuilderAPI_MakeWire myWireProfile = T14_;
	T15_ = (NIM_BOOL)0;
	T15_ = BRepLib::BuildCurves3d(myWireProfile.BRepBuilderAPI_MakeShape::operator TopoDS_Shape());
	result = myWireProfile.BRepBuilderAPI_MakeWire::operator TopoDS_Wire();
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size) {
	void* T1_ = memset(a, v, ((size_t) (size)));
}
static N_INLINE(void, nimZeroMem)(void* p, NI size) {
	nimSetMem__systemZmemory_7(p, ((int) 0), size);
}
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size) {
	void* T1_ = memcpy(dest, source, ((size_t) (size)));
}
N_LIB_PRIVATE N_NIMCALL(void, yeq___sketcher50d954849_66)(NF* obj, NF val) {
	obj[(((NI) 1))- 0] = val;
}
static N_NIMCALL(void, Marker_tySequence__f9aB3gxGPxALrM2IRe7gyQg)(void* p, NI op) {
	tySequence__f9aB3gxGPxALrM2IRe7gyQg* a;
	NI T1_;
	NI T2_;
	a = (tySequence__f9aB3gxGPxALrM2IRe7gyQg*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < (a ? a->len : 0); T1_++) {
	T2_ = (NI)0;
	}
}
static N_INLINE(NI, pluspercent___system_696)(NI x, NI y) {
	NI result;
	result = (NI)0;
	result = ((NI) ((NU)((NU64)(((NU) (x))) + (NU64)(((NU) (y))))));
	return result;
}
static N_INLINE(void, incRef__system_5317)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	(*c).refcount = pluspercent___system_696((*c).refcount, ((NI) 8));
}
static N_INLINE(NI, minuspercent___system_716)(NI x, NI y) {
	NI result;
	result = (NI)0;
	result = ((NI) ((NU)((NU64)(((NU) (x))) - (NU64)(((NU) (y))))));
	return result;
}
static N_INLINE(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell__system_5279)(void* usr) {
	tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* result;
	result = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
	NI T1_ = minuspercent___system_716(((NI) (ptrdiff_t) (usr)), ((NI) 16));
	result = ((tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*) (T1_));
	return result;
}
static N_INLINE(NIM_BOOL, ltpercent___system_1005)(NI x, NI y) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	result = ((NU64)(((NU) (x))) < (NU64)(((NU) (y))));
	return result;
}
static N_INLINE(void, rtlAddZCT__system_5322)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	addZCT__system_5273(gch__system_5226.zct, c);
}
static N_INLINE(void, decRef__system_5324)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	(*c).refcount = minuspercent___system_716((*c).refcount, ((NI) 8));
	{
		NIM_BOOL T3_ = ltpercent___system_1005((*c).refcount, ((NI) 8));
		if (!T3_) goto LA4_;
{		rtlAddZCT__system_5322(c);
}	}
	LA4_: ;
}
static N_INLINE(void, asgnRef)(void** dest, void* src) {
	{
		if (!!((src == NIM_NIL))) goto LA3_;
{		tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T5_ = usrToCell__system_5279(src);
		incRef__system_5317(T5_);
}	}
	LA3_: ;
	{
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
{		tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T10_ = usrToCell__system_5279((*dest));
		decRef__system_5324(T10_);
}	}
	LA8_: ;
	(*dest) = src;
}
static N_NIMCALL(void, Marker_tySequence__GdhZuuACwFC00AwlRIU9b4A)(void* p, NI op) {
	tySequence__GdhZuuACwFC00AwlRIU9b4A* a;
	NI T1_;
	a = (tySequence__GdhZuuACwFC00AwlRIU9b4A*)p;
	T1_ = (NI)0;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_Sketch2dObj__69bjq5HIgQ8lj6TeGoMpO9cQ*, vLine__sketcher50d954849_52)(tyObject_Sketch2dObj__69bjq5HIgQ8lj6TeGoMpO9cQ* skt, NF distance) {
	tyObject_Sketch2dObj__69bjq5HIgQ8lj6TeGoMpO9cQ* result;
	tyArray__Tgy9b6R4KdSrcLohzVAUl8w aPnt1;
	NI T1_;
	tyArray__Tgy9b6R4KdSrcLohzVAUl8w aPnt2;
	NI T3_;
	NI T6_;
{	result = NIM_NIL;
	nimZeroMem((void*)aPnt1, sizeof(tyArray__Tgy9b6R4KdSrcLohzVAUl8w));
	T1_ = (((*skt).points ? (*skt).points->len : 0)-1);
	if (T1_ < 0 || T1_ >= ((*skt).points ? (*skt).points->len : 0)){ raiseIndexError2(T1_,((*skt).points ? (*skt).points->len : 0)-1); }
	nimCopyMem((void*)aPnt1, (NIM_CONST void*)(*skt).points->data[T1_], sizeof(tyArray__Tgy9b6R4KdSrcLohzVAUl8w));
	nimZeroMem((void*)aPnt2, sizeof(tyArray__Tgy9b6R4KdSrcLohzVAUl8w));
	nimCopyMem((void*)aPnt2, (NIM_CONST void*)aPnt1, sizeof(tyArray__Tgy9b6R4KdSrcLohzVAUl8w));
	NF T2_ = y__OOZOOZsrcZlibZsketcherZsketcher50d_23(aPnt2);
	yeq___sketcher50d954849_66(aPnt2, ((NF)(T2_) + (NF)(distance)));
	asgnRef((void**) (&(*skt).points), (tySequence__f9aB3gxGPxALrM2IRe7gyQg*) incrSeqV3((*skt).points, (&NTIseqLpoint50dobjT__f9aB3gxGPxALrM2IRe7gyQg_)));
	T3_ = (*skt).points->len++;
	nimCopyMem((void*)(*skt).points->data[T3_], (NIM_CONST void*)aPnt2, sizeof(tyArray__Tgy9b6R4KdSrcLohzVAUl8w));
	gp_Pnt2d T4_ = pnt2d__OOZOOZsrcZlibZsketcherZsketcher50d_34(aPnt1);
	gp_Pnt2d T5_ = pnt2d__OOZOOZsrcZlibZsketcherZsketcher50d_34(aPnt2);
	TopoDS_Edge e = (BRepBuilderAPI_MakeEdge2d(T4_, T5_));
	asgnRef((void**) (&(*skt).segments), (tySequence__GdhZuuACwFC00AwlRIU9b4A*) incrSeqV3((*skt).segments, (&NTIseqLtopods95edgeT__GdhZuuACwFC00AwlRIU9b4A_)));
	T6_ = (*skt).segments->len++;
	(*skt).segments->data[T6_] = e;
	result = skt;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_Sketch2dObj__69bjq5HIgQ8lj6TeGoMpO9cQ*, threePointsArc__sketcher50d954849_92)(tyObject_Sketch2dObj__69bjq5HIgQ8lj6TeGoMpO9cQ* skt, NI p1x, NF p1y, NF p2x, NF p2y) {
	tyObject_Sketch2dObj__69bjq5HIgQ8lj6TeGoMpO9cQ* result;
	NI T1_;
	tyArray__Tgy9b6R4KdSrcLohzVAUl8w T3_;
	NI T4_;
	tyArray__Tgy9b6R4KdSrcLohzVAUl8w T6_;
	NI T7_;
	TopoDS_Edge T8_;
	NI T9_;
{	result = NIM_NIL;
	T1_ = (((*skt).points ? (*skt).points->len : 0)-1);
	if (T1_ < 0 || T1_ >= ((*skt).points ? (*skt).points->len : 0)){ raiseIndexError2(T1_,((*skt).points ? (*skt).points->len : 0)-1); }
	gp_Pnt2d T2_ = pnt2d__OOZOOZsrcZlibZsketcherZsketcher50d_34((*skt).points->data[T1_]);
	gp_Pnt2d ini = T2_;
	T3_[0] = ((NF) (p1x));
	T3_[1] = p1y;
	asgnRef((void**) (&(*skt).points), (tySequence__f9aB3gxGPxALrM2IRe7gyQg*) incrSeqV3((*skt).points, (&NTIseqLpoint50dobjT__f9aB3gxGPxALrM2IRe7gyQg_)));
	T4_ = (*skt).points->len++;
	nimCopyMem((void*)(*skt).points->data[T4_], (NIM_CONST void*)T3_, sizeof(tyArray__Tgy9b6R4KdSrcLohzVAUl8w));
	float T5_ = toCfloat__sketcher50d954849_115(p1x);
	gp_Pnt2d middle(T5_, ((float) (p1y)));
	T6_[0] = p2x;
	T6_[1] = p2y;
	asgnRef((void**) (&(*skt).points), (tySequence__f9aB3gxGPxALrM2IRe7gyQg*) incrSeqV3((*skt).points, (&NTIseqLpoint50dobjT__f9aB3gxGPxALrM2IRe7gyQg_)));
	T7_ = (*skt).points->len++;
	nimCopyMem((void*)(*skt).points->data[T7_], (NIM_CONST void*)T6_, sizeof(tyArray__Tgy9b6R4KdSrcLohzVAUl8w));
	gp_Pnt2d latest(((float) (p2x)), ((float) (p2y)));
	TY__gr9cHpXf2T9bJg9bMQ9cd8A9cDQ arc = GCE2d_MakeArcOfCircle(ini, middle, latest).Value();
	BRepBuilderAPI_MakeEdge2d e(arc);
	T8_ = (e);
	asgnRef((void**) (&(*skt).segments), (tySequence__GdhZuuACwFC00AwlRIU9b4A*) incrSeqV3((*skt).segments, (&NTIseqLtopods95edgeT__GdhZuuACwFC00AwlRIU9b4A_)));
	T9_ = (*skt).segments->len++;
	(*skt).segments->data[T9_] = T8_;
	result = skt;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
static N_NIMCALL(void, Marker_tySequence__0fMAnTwz5AxtkqIdipBt4w)(void* p, NI op) {
	tySequence__0fMAnTwz5AxtkqIdipBt4w* a;
	NI T1_;
	a = (tySequence__0fMAnTwz5AxtkqIdipBt4w*)p;
	T1_ = (NI)0;
}
static N_NIMCALL(void, Marker_tySequence__uglp2GtOV9bH7gMNc6PppLg)(void* p, NI op) {
	tySequence__uglp2GtOV9bH7gMNc6PppLg* a;
	NI T1_;
	a = (tySequence__uglp2GtOV9bH7gMNc6PppLg*)p;
	T1_ = (NI)0;
}
static N_NIMCALL(void, Marker_tyRef__UPfoI3fQ9ao79bAcCuk9abq1w)(void* p, NI op) {
	tyObject_Sketch2dObj__69bjq5HIgQ8lj6TeGoMpO9cQ* a;
	a = (tyObject_Sketch2dObj__69bjq5HIgQ8lj6TeGoMpO9cQ*)p;
	nimGCvisit((void*)(*a).points, op);
	nimGCvisit((void*)(*a).segments, op);
	nimGCvisit((void*)(*a).wires, op);
	nimGCvisit((void*)(*a).shapes, op);
}
N_LIB_PRIVATE N_NIMCALL(tyObject_Sketch2dObj__69bjq5HIgQ8lj6TeGoMpO9cQ*, start__sketcher50d954849_6)(NF x, NI y) {
	tyObject_Sketch2dObj__69bjq5HIgQ8lj6TeGoMpO9cQ* result;
	tyArray__Tgy9b6R4KdSrcLohzVAUl8w T1_;
	NI T2_;
	result = NIM_NIL;
	result = new__sketcher50d954849_12();
	T1_[0] = x;
	T1_[1] = ((NF) (y));
	asgnRef((void**) (&(*result).points), (tySequence__f9aB3gxGPxALrM2IRe7gyQg*) incrSeqV3((*result).points, (&NTIseqLpoint50dobjT__f9aB3gxGPxALrM2IRe7gyQg_)));
	T2_ = (*result).points->len++;
	nimCopyMem((void*)(*result).points->data[T2_], (NIM_CONST void*)T1_, sizeof(tyArray__Tgy9b6R4KdSrcLohzVAUl8w));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(TopoDS_Shape, cylinder__sketcher50d954849_222)(NF radius, NF height, gp_Pnt position, gp_Dir axis) {
	TopoDS_Shape result;
{	gp_Ax2 cylAx2(position, axis);
	result = BRepPrimAPI_MakeCylinder(cylAx2, ((float) (radius)), ((float) (height))).Shape();
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(TopoDS_Shape, shell__sketcher50d954849_250)(TopoDS_Shape shp, NF offset, TopoDS_Face* removePlains, NI removePlainsLen_0, NF tolerance) {
	TopoDS_Shape result;
	tySequence__p3ejDZUwgffAWrdMTTu9c7Q* planes;
	Message_ProgressRange T6_;
	{
		tySequence__p3ejDZUwgffAWrdMTTu9c7Q* resultX60gensym10_;
		NI iX60gensym10_ = ((NI) 0);
		if ((removePlainsLen_0) < ((NI) 0) || (removePlainsLen_0) > ((NI) IL64(9223372036854775807))){ raiseRangeErrorI(removePlainsLen_0, ((NI) 0), ((NI) IL64(9223372036854775807))); }
		resultX60gensym10_ = newSeq__sketcher50d954849_405(((NI) (removePlainsLen_0)));
		{
			TopoDS_Face* itX60gensym10_;
			itX60gensym10_ = (TopoDS_Face*)0;
			NI i = ((NI) 0);
			{
				while (1) {
					NI TM__wo5SM9aq6i8S8F5tc6S9bIHA_5;
					NI TM__wo5SM9aq6i8S8F5tc6S9bIHA_6;
					if (!(i < removePlainsLen_0)) goto LA4;
					if (i < 0 || i >= removePlainsLen_0){ raiseIndexError2(i,removePlainsLen_0-1); }
					itX60gensym10_ = (&removePlains[i]);
					if (iX60gensym10_ < 0 || iX60gensym10_ >= (resultX60gensym10_ ? resultX60gensym10_->len : 0)){ raiseIndexError2(iX60gensym10_,(resultX60gensym10_ ? resultX60gensym10_->len : 0)-1); }
					resultX60gensym10_->data[iX60gensym10_] = (*itX60gensym10_);
					if (nimAddInt(iX60gensym10_, ((NI) 1), &TM__wo5SM9aq6i8S8F5tc6S9bIHA_5)) { raiseOverflow(); };
					iX60gensym10_ = (NI)(TM__wo5SM9aq6i8S8F5tc6S9bIHA_5);
					if (nimAddInt(i, ((NI) 1), &TM__wo5SM9aq6i8S8F5tc6S9bIHA_6)) { raiseOverflow(); };
					i = (NI)(TM__wo5SM9aq6i8S8F5tc6S9bIHA_6);
				} LA4: ;
			}
		}
		planes = resultX60gensym10_;
	}
	TY__GIqsjlKJHsTq0jbUI9bnu9aw T5_ = toTopTools_ListOfShape__sketcher50d954849_427(planes);
	result = makeThickSolidByJoin__OOZOOZsrcZlibZtkoffsetZtkoffset_3(shp, T5_, offset, tolerance, ((BRepOffset_Mode) 0), NIM_FALSE, NIM_FALSE, ((GeomAbs_JoinType) 0), NIM_FALSE, T6_);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatssrcatslibatssketcheratssketcher2ddotnim_DatInit000)(void) {
static TNimNode* TM__wo5SM9aq6i8S8F5tc6S9bIHA_4_4[4];
static TNimNode TM__wo5SM9aq6i8S8F5tc6S9bIHA_0[5];
NTIpoint50dobj__Tgy9b6R4KdSrcLohzVAUl8w_.size = sizeof(tyArray__Tgy9b6R4KdSrcLohzVAUl8w);
NTIpoint50dobj__Tgy9b6R4KdSrcLohzVAUl8w_.align = NIM_ALIGNOF(tyArray__Tgy9b6R4KdSrcLohzVAUl8w);
NTIpoint50dobj__Tgy9b6R4KdSrcLohzVAUl8w_.kind = 16;
NTIpoint50dobj__Tgy9b6R4KdSrcLohzVAUl8w_.base = (&NTIfloat__w9bl9a1ul9ctRJWiMl9cNnIMvg_);
NTIpoint50dobj__Tgy9b6R4KdSrcLohzVAUl8w_.flags = 1;
NTIseqLpoint50dobjT__f9aB3gxGPxALrM2IRe7gyQg_.size = sizeof(tySequence__f9aB3gxGPxALrM2IRe7gyQg*);
NTIseqLpoint50dobjT__f9aB3gxGPxALrM2IRe7gyQg_.align = NIM_ALIGNOF(tySequence__f9aB3gxGPxALrM2IRe7gyQg*);
NTIseqLpoint50dobjT__f9aB3gxGPxALrM2IRe7gyQg_.kind = 24;
NTIseqLpoint50dobjT__f9aB3gxGPxALrM2IRe7gyQg_.base = (&NTIpoint50dobj__Tgy9b6R4KdSrcLohzVAUl8w_);
NTIseqLpoint50dobjT__f9aB3gxGPxALrM2IRe7gyQg_.marker = Marker_tySequence__f9aB3gxGPxALrM2IRe7gyQg;
NTIseqLtopods95edgeT__GdhZuuACwFC00AwlRIU9b4A_.size = sizeof(tySequence__GdhZuuACwFC00AwlRIU9b4A*);
NTIseqLtopods95edgeT__GdhZuuACwFC00AwlRIU9b4A_.align = NIM_ALIGNOF(tySequence__GdhZuuACwFC00AwlRIU9b4A*);
NTIseqLtopods95edgeT__GdhZuuACwFC00AwlRIU9b4A_.kind = 24;
NTIseqLtopods95edgeT__GdhZuuACwFC00AwlRIU9b4A_.base = (&NTItopods95edge__jOPcFChOFG9cvA9a2u619aaSA_);
NTIseqLtopods95edgeT__GdhZuuACwFC00AwlRIU9b4A_.marker = Marker_tySequence__GdhZuuACwFC00AwlRIU9b4A;
NTIsketch50dobj__69bjq5HIgQ8lj6TeGoMpO9cQ_.size = sizeof(tyObject_Sketch2dObj__69bjq5HIgQ8lj6TeGoMpO9cQ);
NTIsketch50dobj__69bjq5HIgQ8lj6TeGoMpO9cQ_.align = NIM_ALIGNOF(tyObject_Sketch2dObj__69bjq5HIgQ8lj6TeGoMpO9cQ);
NTIsketch50dobj__69bjq5HIgQ8lj6TeGoMpO9cQ_.kind = 18;
NTIsketch50dobj__69bjq5HIgQ8lj6TeGoMpO9cQ_.base = 0;
TM__wo5SM9aq6i8S8F5tc6S9bIHA_4_4[0] = &TM__wo5SM9aq6i8S8F5tc6S9bIHA_0[1];
TM__wo5SM9aq6i8S8F5tc6S9bIHA_0[1].kind = 1;
TM__wo5SM9aq6i8S8F5tc6S9bIHA_0[1].offset = offsetof(tyObject_Sketch2dObj__69bjq5HIgQ8lj6TeGoMpO9cQ, points);
TM__wo5SM9aq6i8S8F5tc6S9bIHA_0[1].typ = (&NTIseqLpoint50dobjT__f9aB3gxGPxALrM2IRe7gyQg_);
TM__wo5SM9aq6i8S8F5tc6S9bIHA_0[1].name = "points";
TM__wo5SM9aq6i8S8F5tc6S9bIHA_4_4[1] = &TM__wo5SM9aq6i8S8F5tc6S9bIHA_0[2];
TM__wo5SM9aq6i8S8F5tc6S9bIHA_0[2].kind = 1;
TM__wo5SM9aq6i8S8F5tc6S9bIHA_0[2].offset = offsetof(tyObject_Sketch2dObj__69bjq5HIgQ8lj6TeGoMpO9cQ, segments);
TM__wo5SM9aq6i8S8F5tc6S9bIHA_0[2].typ = (&NTIseqLtopods95edgeT__GdhZuuACwFC00AwlRIU9b4A_);
TM__wo5SM9aq6i8S8F5tc6S9bIHA_0[2].name = "segments";
TM__wo5SM9aq6i8S8F5tc6S9bIHA_4_4[2] = &TM__wo5SM9aq6i8S8F5tc6S9bIHA_0[3];
NTIseqLtopods95wireT__0fMAnTwz5AxtkqIdipBt4w_.size = sizeof(tySequence__0fMAnTwz5AxtkqIdipBt4w*);
NTIseqLtopods95wireT__0fMAnTwz5AxtkqIdipBt4w_.align = NIM_ALIGNOF(tySequence__0fMAnTwz5AxtkqIdipBt4w*);
NTIseqLtopods95wireT__0fMAnTwz5AxtkqIdipBt4w_.kind = 24;
NTIseqLtopods95wireT__0fMAnTwz5AxtkqIdipBt4w_.base = (&NTItopods95wire__iXlfJUv20QZLaQkRrdvITg_);
NTIseqLtopods95wireT__0fMAnTwz5AxtkqIdipBt4w_.marker = Marker_tySequence__0fMAnTwz5AxtkqIdipBt4w;
TM__wo5SM9aq6i8S8F5tc6S9bIHA_0[3].kind = 1;
TM__wo5SM9aq6i8S8F5tc6S9bIHA_0[3].offset = offsetof(tyObject_Sketch2dObj__69bjq5HIgQ8lj6TeGoMpO9cQ, wires);
TM__wo5SM9aq6i8S8F5tc6S9bIHA_0[3].typ = (&NTIseqLtopods95wireT__0fMAnTwz5AxtkqIdipBt4w_);
TM__wo5SM9aq6i8S8F5tc6S9bIHA_0[3].name = "wires";
TM__wo5SM9aq6i8S8F5tc6S9bIHA_4_4[3] = &TM__wo5SM9aq6i8S8F5tc6S9bIHA_0[4];
NTIseqLtopods95shapeT__uglp2GtOV9bH7gMNc6PppLg_.size = sizeof(tySequence__uglp2GtOV9bH7gMNc6PppLg*);
NTIseqLtopods95shapeT__uglp2GtOV9bH7gMNc6PppLg_.align = NIM_ALIGNOF(tySequence__uglp2GtOV9bH7gMNc6PppLg*);
NTIseqLtopods95shapeT__uglp2GtOV9bH7gMNc6PppLg_.kind = 24;
NTIseqLtopods95shapeT__uglp2GtOV9bH7gMNc6PppLg_.base = (&NTItopods95shape__EbhlUdygTvfLelaziGdVeQ_);
NTIseqLtopods95shapeT__uglp2GtOV9bH7gMNc6PppLg_.marker = Marker_tySequence__uglp2GtOV9bH7gMNc6PppLg;
TM__wo5SM9aq6i8S8F5tc6S9bIHA_0[4].kind = 1;
TM__wo5SM9aq6i8S8F5tc6S9bIHA_0[4].offset = offsetof(tyObject_Sketch2dObj__69bjq5HIgQ8lj6TeGoMpO9cQ, shapes);
TM__wo5SM9aq6i8S8F5tc6S9bIHA_0[4].typ = (&NTIseqLtopods95shapeT__uglp2GtOV9bH7gMNc6PppLg_);
TM__wo5SM9aq6i8S8F5tc6S9bIHA_0[4].name = "shapes";
TM__wo5SM9aq6i8S8F5tc6S9bIHA_0[0].len = 4; TM__wo5SM9aq6i8S8F5tc6S9bIHA_0[0].kind = 2; TM__wo5SM9aq6i8S8F5tc6S9bIHA_0[0].sons = &TM__wo5SM9aq6i8S8F5tc6S9bIHA_4_4[0];
NTIsketch50dobj__69bjq5HIgQ8lj6TeGoMpO9cQ_.node = &TM__wo5SM9aq6i8S8F5tc6S9bIHA_0[0];
NTIsketch50dref__UPfoI3fQ9ao79bAcCuk9abq1w_.size = sizeof(tyObject_Sketch2dObj__69bjq5HIgQ8lj6TeGoMpO9cQ*);
NTIsketch50dref__UPfoI3fQ9ao79bAcCuk9abq1w_.align = NIM_ALIGNOF(tyObject_Sketch2dObj__69bjq5HIgQ8lj6TeGoMpO9cQ*);
NTIsketch50dref__UPfoI3fQ9ao79bAcCuk9abq1w_.kind = 22;
NTIsketch50dref__UPfoI3fQ9ao79bAcCuk9abq1w_.base = (&NTIsketch50dobj__69bjq5HIgQ8lj6TeGoMpO9cQ_);
NTIsketch50dref__UPfoI3fQ9ao79bAcCuk9abq1w_.marker = Marker_tyRef__UPfoI3fQ9ao79bAcCuk9abq1w;
}

