/* Generated by Nim Compiler v1.6.10 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   g++ -c -std=gnu++14 -funsigned-char  -w -fmax-errors=3 -fpermissive -I/usr/include/opencascade/ -I/usr/import/opencascade/ -O3 -fno-strict-aliasing -fno-ident   -I/home/jose/.choosenim/toolchains/nim-1.6.10/lib -I/home/jose/src/nimlang/occt.nim/examples/api -o /home/jose/src/nimlang/occt.nim/examples/api/borrame/@m..@s..@ssrc@slib@sprimitives@spoint.nim.cpp.o /home/jose/src/nimlang/occt.nim/examples/api/borrame/@m..@s..@ssrc@slib@sprimitives@spoint.nim.cpp */
#define NIM_INTBITS 64

#include "nimbase.h"
#include "gp_Pnt.hxx"
#include "gp_Dir.hxx"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
N_LIB_PRIVATE N_NIMCALL(float, toCfloat__sketcher50d954849_115)(NI val) {
	float result;
	result = (float)0;
	result = ((float) (val));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(gp_Pnt, pnt__sketcher50d954849_197)(NI x, NI y, NF z) {
	gp_Pnt result;
	result = gp_Pnt(((float) (x)), ((float) (y)), ((float) (z)));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(gp_Dir, dir__sketcher50d954849_205)(NI x, NI y, NI z) {
	gp_Dir result;
	result = gp_Dir(((float) (x)), ((float) (y)), ((float) (z)));
	return result;
}
