/* Generated by Nim Compiler v1.6.10 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   g++ -c -std=gnu++14 -funsigned-char  -w -fmax-errors=3 -fpermissive -I/usr/include/opencascade/ -I/usr/import/opencascade/ -O3 -fno-strict-aliasing -fno-ident   -I/home/jose/.choosenim/toolchains/nim-1.6.10/lib -I/home/jose/src/nimlang/occt.nim/examples/api -o /home/jose/src/nimlang/occt.nim/examples/api/borrame/@msketcher2d_01.nim.cpp.o /home/jose/src/nimlang/occt.nim/examples/api/borrame/@msketcher2d_01.nim.cpp */
#define NIM_INTBITS 64

#include "nimbase.h"
#include "TopoDS_Shape.hxx"
#include "TopoDS_Wire.hxx"
#include "gp_Pnt.hxx"
#include "gp_Dir.hxx"
#include "BRepBuilderAPI_MakeShape.hxx"
#include "BRepAlgoAPI_Fuse.hxx"
#include "TopoDS_Face.hxx"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
struct tyObject_Sketch2dObj__69bjq5HIgQ8lj6TeGoMpO9cQ;
struct TNimType;
struct TNimNode;
struct tySequence__p3ejDZUwgffAWrdMTTu9c7Q;
struct TGenericSeq;
struct NimStringDesc;
typedef NU8 tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc__ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
NI align;
tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc__ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct TGenericSeq {
NI len;
NI reserved;
};
typedef TopoDS_Face tyArray__4hnjzjoWqGQxHLmz0LFagw[1];
struct NimStringDesc : public TGenericSeq {
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tySequence__p3ejDZUwgffAWrdMTTu9c7Q : TGenericSeq {
  TopoDS_Face data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(void, main__sketcher50d954849_2)(void);
N_LIB_PRIVATE N_NIMCALL(TopoDS_Shape, fillet__sketcher50d954849_178)(TopoDS_Shape aBody, NF radius);
N_LIB_PRIVATE N_NIMCALL(TopoDS_Shape, extrude__sketcher50d954849_144)(TopoDS_Wire aWire, NF height);
N_LIB_PRIVATE N_NIMCALL(TopoDS_Wire, closeWithMirror__OOZOOZsrcZlibZsketcherZsketcher50d_87)(tyObject_Sketch2dObj__69bjq5HIgQ8lj6TeGoMpO9cQ* skt);
N_LIB_PRIVATE N_NIMCALL(tyObject_Sketch2dObj__69bjq5HIgQ8lj6TeGoMpO9cQ*, vLine__sketcher50d954849_52)(tyObject_Sketch2dObj__69bjq5HIgQ8lj6TeGoMpO9cQ* skt, NF distance);
N_LIB_PRIVATE N_NIMCALL(tyObject_Sketch2dObj__69bjq5HIgQ8lj6TeGoMpO9cQ*, threePointsArc__sketcher50d954849_92)(tyObject_Sketch2dObj__69bjq5HIgQ8lj6TeGoMpO9cQ* skt, NI p1x, NF p1y, NF p2x, NF p2y);
N_LIB_PRIVATE N_NIMCALL(tyObject_Sketch2dObj__69bjq5HIgQ8lj6TeGoMpO9cQ*, start__sketcher50d954849_6)(NF x, NI y);
N_LIB_PRIVATE N_NIMCALL(TopoDS_Shape, cylinder__sketcher50d954849_222)(NF radius, NF height, gp_Pnt position, gp_Dir axis);
N_LIB_PRIVATE N_NIMCALL(gp_Pnt, pnt__sketcher50d954849_197)(NI x, NI y, NF z);
N_LIB_PRIVATE N_NIMCALL(gp_Dir, dir__sketcher50d954849_205)(NI x, NI y, NI z);
N_LIB_PRIVATE N_NIMCALL(TopoDS_Shape, shell__sketcher50d954849_250)(TopoDS_Shape shp, NF offset, TopoDS_Face* removePlains, NI removePlainsLen_0, NF tolerance);
static N_NIMCALL(void, Marker_tySequence__p3ejDZUwgffAWrdMTTu9c7Q)(void* p, NI op);
N_LIB_PRIVATE N_NIMCALL(TopoDS_Face, getPlaneZmax__OOZOOZsrcZlibZexplorerZexplorer_41)(TopoDS_Shape body);
N_LIB_PRIVATE N_NIMCALL(void, toSTEP__sketcher50d954849_491)(TopoDS_Shape solid, NimStringDesc* fname);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_LIB_PRIVATE N_NOINLINE(void, nimGC_setStackBottom)(void* theStackBottom);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsdotchoosenimatstoolchainsatsnimminus1dot6dot10atslibatssystemdotnim_DatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsdotchoosenimatstoolchainsatsnimminus1dot6dot10atslibatssystemdotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatssrcatswrapperatstkbrepatstopodsatstopods_typesdotnim_DatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatssrcatslibatssketcheratssketcher2ddotnim_DatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atmsketcher2d01dotnim_DatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void);
extern TNimType NTItopods95face__eb9aQZydUaK6E9b2LeoS4WBw_;
N_LIB_PRIVATE TNimType NTIseqLtopods95faceT__p3ejDZUwgffAWrdMTTu9c7Q_;
STRING_LITERAL(TM__QioUbPY6kz4XN0blMKwcwA_2, "borrame.stp", 11);
static N_NIMCALL(void, Marker_tySequence__p3ejDZUwgffAWrdMTTu9c7Q)(void* p, NI op) {
	tySequence__p3ejDZUwgffAWrdMTTu9c7Q* a;
	NI T1_;
	a = (tySequence__p3ejDZUwgffAWrdMTTu9c7Q*)p;
	T1_ = (NI)0;
}
N_LIB_PRIVATE N_NIMCALL(void, main__sketcher50d954849_2)(void) {
	tyArray__4hnjzjoWqGQxHLmz0LFagw T11_;
	NF myWidth = 50.0;
	NF myThickness = 20.0;
	NF myHeight = 70.0;
	tyObject_Sketch2dObj__69bjq5HIgQ8lj6TeGoMpO9cQ* T1_ = start__sketcher50d954849_6(((NF)(-(myWidth)) / (NF)(2.0)), ((NI) 0));
	tyObject_Sketch2dObj__69bjq5HIgQ8lj6TeGoMpO9cQ* T2_ = vLine__sketcher50d954849_52(T1_, ((NF)(-(myThickness)) / (NF)(4.0)));
	tyObject_Sketch2dObj__69bjq5HIgQ8lj6TeGoMpO9cQ* T3_ = threePointsArc__sketcher50d954849_92(T2_, ((NI) 0), ((NF)(-(myThickness)) / (NF)(2.0)), ((NF)(myWidth) / (NF)(2.0)), ((NF)(-(myThickness)) / (NF)(4.0)));
	tyObject_Sketch2dObj__69bjq5HIgQ8lj6TeGoMpO9cQ* T4_ = vLine__sketcher50d954849_52(T3_, ((NF)(myThickness) / (NF)(4.0)));
	TopoDS_Wire T5_ = closeWithMirror__OOZOOZsrcZlibZsketcherZsketcher50d_87(T4_);
	TopoDS_Shape T6_ = extrude__sketcher50d954849_144(T5_, myHeight);
	TopoDS_Shape T7_ = fillet__sketcher50d954849_178(T6_, ((NF)(myThickness) / (NF)(12.0)));
	TopoDS_Shape myBody = T7_;
	NF myNeckRadius = ((NF)(myThickness) / (NF)(4.0));
	NF myNeckHeight = ((NF)(myHeight) / (NF)(10.0));
	gp_Pnt T8_ = pnt__sketcher50d954849_197(((NI) 0), ((NI) 0), myHeight);
	gp_Dir T9_ = dir__sketcher50d954849_205(((NI) 0), ((NI) 0), ((NI) 1));
	TopoDS_Shape T10_ = cylinder__sketcher50d954849_222(myNeckRadius, myNeckHeight, T8_, T9_);
	TopoDS_Shape myNeck = T10_;
	myBody = BRepAlgoAPI_Fuse(myBody, myNeck).BRepBuilderAPI_MakeShape::operator TopoDS_Shape();
	T11_[0] = getPlaneZmax__OOZOOZsrcZlibZexplorerZexplorer_41(myBody);
	myBody = shell__sketcher50d954849_250(myBody, ((NF)(-(myThickness)) / (NF)(50.0)), T11_, 1, 0.001);
	toSTEP__sketcher50d954849_491(myBody, ((NimStringDesc*) &TM__QioUbPY6kz4XN0blMKwcwA_2));
}
static N_INLINE(void, initStackBottomWith)(void* locals) {
	nimGC_setStackBottom(locals);
}

N_LIB_PRIVATE void PreMainInner(void) {
}

N_LIB_PRIVATE int cmdCount;
N_LIB_PRIVATE char** cmdLine;
N_LIB_PRIVATE char** gEnv;
N_LIB_PRIVATE void PreMain(void) {
	void (*volatile inner)(void);
	inner = PreMainInner;
	atmdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsdotchoosenimatstoolchainsatsnimminus1dot6dot10atslibatssystemdotnim_DatInit000();
	initStackBottomWith((void *)&inner);
	atmdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsdotchoosenimatstoolchainsatsnimminus1dot6dot10atslibatssystemdotnim_Init000();
	atmdotdotatsdotdotatssrcatswrapperatstkbrepatstopodsatstopods_typesdotnim_DatInit000();
	atmdotdotatsdotdotatssrcatslibatssketcheratssketcher2ddotnim_DatInit000();
	atmsketcher2d01dotnim_DatInit000();
	(*inner)();
}

N_LIB_PRIVATE N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void) {
{
	main__sketcher50d954849_2();
}
}

N_LIB_PRIVATE N_NIMCALL(void, atmsketcher2d01dotnim_DatInit000)(void) {
NTIseqLtopods95faceT__p3ejDZUwgffAWrdMTTu9c7Q_.size = sizeof(tySequence__p3ejDZUwgffAWrdMTTu9c7Q*);
NTIseqLtopods95faceT__p3ejDZUwgffAWrdMTTu9c7Q_.align = NIM_ALIGNOF(tySequence__p3ejDZUwgffAWrdMTTu9c7Q*);
NTIseqLtopods95faceT__p3ejDZUwgffAWrdMTTu9c7Q_.kind = 24;
NTIseqLtopods95faceT__p3ejDZUwgffAWrdMTTu9c7Q_.base = (&NTItopods95face__eb9aQZydUaK6E9b2LeoS4WBw_);
NTIseqLtopods95faceT__p3ejDZUwgffAWrdMTTu9c7Q_.marker = Marker_tySequence__p3ejDZUwgffAWrdMTTu9c7Q;
}

