{.passL:"-lTKXCAF".}
{.passC:"-I/usr/include/opencascade/".}

import xcafdimtolobjects_datamapoftolerancedatum
import xcafdimtolobjects_datummodifierssequence
import xcafdimtolobjects_datummodifwithvalue
import xcafdimtolobjects_datumobject
import xcafdimtolobjects_datumobjectsequence
import xcafdimtolobjects_datumsinglemodif
import xcafdimtolobjects_datumtargettype
import xcafdimtolobjects_dimensionformvariance
import xcafdimtolobjects_dimensiongrade
import xcafdimtolobjects_dimensionmodif
import xcafdimtolobjects_dimensionmodifierssequence
import xcafdimtolobjects_dimensionobject
import xcafdimtolobjects_dimensionobjectsequence
import xcafdimtolobjects_dimensionqualifier
import xcafdimtolobjects_dimensiontype
import xcafdimtolobjects_geomtolerancematreqmodif
import xcafdimtolobjects_geomtolerancemodif
import xcafdimtolobjects_geomtolerancemodifierssequence
import xcafdimtolobjects_geomtoleranceobject
import xcafdimtolobjects_geomtoleranceobjectsequence
import xcafdimtolobjects_geomtolerancetype
import xcafdimtolobjects_geomtolerancetypevalue
import xcafdimtolobjects_geomtolerancezonemodif
import xcafdimtolobjects_tolerancezoneaffectedplane
import xcafdimtolobjects_tool
import xcafdimtolobjects_types


export xcafdimtolobjects_datamapoftolerancedatum
export xcafdimtolobjects_datummodifierssequence
export xcafdimtolobjects_datummodifwithvalue
export xcafdimtolobjects_datumobject
export xcafdimtolobjects_datumobjectsequence
export xcafdimtolobjects_datumsinglemodif
export xcafdimtolobjects_datumtargettype
export xcafdimtolobjects_dimensionformvariance
export xcafdimtolobjects_dimensiongrade
export xcafdimtolobjects_dimensionmodif
export xcafdimtolobjects_dimensionmodifierssequence
export xcafdimtolobjects_dimensionobject
export xcafdimtolobjects_dimensionobjectsequence
export xcafdimtolobjects_dimensionqualifier
export xcafdimtolobjects_dimensiontype
export xcafdimtolobjects_geomtolerancematreqmodif
export xcafdimtolobjects_geomtolerancemodif
export xcafdimtolobjects_geomtolerancemodifierssequence
export xcafdimtolobjects_geomtoleranceobject
export xcafdimtolobjects_geomtoleranceobjectsequence
export xcafdimtolobjects_geomtolerancetype
export xcafdimtolobjects_geomtolerancetypevalue
export xcafdimtolobjects_geomtolerancezonemodif
export xcafdimtolobjects_tolerancezoneaffectedplane
export xcafdimtolobjects_tool
export xcafdimtolobjects_types
