{.passL:"-lTKernel".}
{.passC:"-I/usr/include/opencascade/" .}

import standard_types


import standard
#include standard/standard_abortivetransaction
import standard_address
import standard_arraystreambuffer
import standard_assert
import standard_atomic
import standard_boolean
import standard_byte
import standard_character
import standard_clocalesentry
import standard_condition
#include standard/standard_constructionerror
import standard_cstring
import standard_definealloc
import standard_defineexception
import standard_definehandle
#include standard/standard_dimensionerror
#include standard/standard_dimensionmismatch
#include standard/standard_dividebyzero
#include standard/standard_domainerror
#include standard/standard_dump
import standard_errorhandler
import standard_extcharacter
import standard_extstring
import standard_failure
import standard_guid
import standard_handle
import standard_handlerstatus
#include standard/standard_immutableobject
import standard_integer
#import standard_istream
import standard_jmpbuf
#include standard/standard_licenseerror
#include standard/standard_licensenotfound
import standard_macro
import standard_math
import standard_mmgropt
import standard_mmgrraw
import standard_mmgrroot
import standard_mmgrtbballoc
#include standard/standard_multiplydefined
import standard_mutex
#include standard/standard_negativevalue
#include standard/standard_nomoreobject
#include standard/standard_nosuchobject
#include standard/standard_notimplemented
#include standard/standard_nullobject
#include standard/standard_nullvalue
#include standard/standard_numericerror
#import standard_ostream
#include standard/standard_outofmemory
#include standard/standard_outofrange
#include standard/standard_overflow
#import standard_pbyte
import standard_pcharacter
#import standard_perrorhandler
import standard_persistent
#import standard_pextcharacter
import standard_primitivetypes
#include standard/standard_programerror
#include standard/standard_rangeerror
import standard_readbuffer
import standard_readlinebuffer
import standard_real
import standard_shortreal
import standard_size
#import standard_sstream
import standard_std
#import standard_stream
import standard_threadid
import standard_time
#include standard/standard_toomanyusers
import standard_transient
import standard_type
import standard_typedef
#include standard/standard_typemismatch
#include standard/standard_underflow
import standard_uuid
import standard_version
#include standard/standard_warningdisablefunctioncast
#include standard/standard_warningsdisable
#include standard/standard_warningsrestore

export standard_types, standard, standard_address, standard_arraystreambuffer
export standard_assert, standard_atomic, standard_boolean, standard_byte
export standard_character, standard_clocalesentry, standard_condition
export standard_cstring, standard_definealloc, standard_defineexception
export standard_definehandle, standard_errorhandler, standard_extcharacter
export standard_extstring, standard_failure, standard_guid, standard_handle
export standard_handlerstatus, standard_integer
export standard_jmpbuf, standard_macro, standard_math, standard_mmgropt
export standard_mmgrraw, standard_mmgrroot, standard_mmgrtbballoc, standard_mutex
export standard_pcharacter
export standard_persistent, standard_primitivetypes
export standard_readbuffer, standard_readlinebuffer, standard_real
export standard_shortreal, standard_size, standard_std
export standard_threadid, standard_time, standard_transient
export standard_type, standard_typedef, standard_uuid, standard_version