{.passL:"-lTKernel".}
{.passC:"-I/usr/include/opencascade/" .}

import standard/standard_types


import standard/standard
#include standard/standard_abortivetransaction
import standard/standard_address
import standard/standard_arraystreambuffer
import standard/standard_assert
import standard/standard_atomic
import standard/standard_boolean
import standard/standard_byte
import standard/standard_character
import standard/standard_clocalesentry
import standard/standard_condition
#include standard/standard_constructionerror
import standard/standard_cstring
import standard/standard_definealloc
import standard/standard_defineexception
import standard/standard_definehandle
#include standard/standard_dimensionerror
#include standard/standard_dimensionmismatch
#include standard/standard_dividebyzero
#include standard/standard_domainerror
#include standard/standard_dump
import standard/standard_errorhandler
import standard/standard_extcharacter
import standard/standard_extstring
import standard/standard_failure
import standard/standard_guid
import standard/standard_handle
import standard/standard_handlerstatus
#include standard/standard_immutableobject
import standard/standard_integer
#import standard/standard_istream
import standard/standard_jmpbuf
#include standard/standard_licenseerror
#include standard/standard_licensenotfound
import standard/standard_macro
import standard/standard_math
import standard/standard_mmgropt
import standard/standard_mmgrraw
import standard/standard_mmgrroot
import standard/standard_mmgrtbballoc
#include standard/standard_multiplydefined
import standard/standard_mutex
#include standard/standard_negativevalue
#include standard/standard_nomoreobject
#include standard/standard_nosuchobject
#include standard/standard_notimplemented
#include standard/standard_nullobject
#include standard/standard_nullvalue
#include standard/standard_numericerror
#import standard/standard_ostream
#include standard/standard_outofmemory
#include standard/standard_outofrange
#include standard/standard_overflow
#import standard/standard_pbyte
import standard/standard_pcharacter
#import standard/standard_perrorhandler
import standard/standard_persistent
#import standard/standard_pextcharacter
import standard/standard_primitivetypes
#include standard/standard_programerror
#include standard/standard_rangeerror
import standard/standard_readbuffer
import standard/standard_readlinebuffer
import standard/standard_real
import standard/standard_shortreal
import standard/standard_size
#import standard/standard_sstream
import standard/standard_std
#import standard/standard_stream
import standard/standard_threadid
import standard/standard_time
#include standard/standard_toomanyusers
import standard/standard_transient
import standard/standard_type
import standard/standard_typedef
#include standard/standard_typemismatch
#include standard/standard_underflow
import standard/standard_uuid
import standard/standard_version
#include standard/standard_warningdisablefunctioncast
#include standard/standard_warningsdisable
#include standard/standard_warningsrestore

export standard_types, standard, standard_address, standard_arraystreambuffer
export standard_assert, standard_atomic, standard_boolean, standard_byte
export standard_character, standard_clocalesentry, standard_condition
export standard_cstring, standard_definealloc, standard_defineexception
export standard_definehandle, standard_errorhandler, standard_extcharacter
export standard_extstring, standard_failure, standard_guid, standard_handle
export standard_handlerstatus, standard_integer
export standard_jmpbuf, standard_macro, standard_math, standard_mmgropt
export standard_mmgrraw, standard_mmgrroot, standard_mmgrtbballoc, standard_mutex
export standard_pcharacter
export standard_persistent, standard_primitivetypes
export standard_readbuffer, standard_readlinebuffer, standard_real
export standard_shortreal, standard_size, standard_std
export standard_threadid, standard_time, standard_transient
export standard_type, standard_typedef, standard_uuid, standard_version