{.passL:"-lTKernel".}
{.passC:"-I/usr/include/opencascade/" .}
#{.experimental: "codeReordering".}

when defined(windows):
  const tkernel* = "TKernel.dll"
elif defined(macosx):
  const tkernel* = "libTKernel.dylib"
else:
  const tkernel* = "libTKernel.so" 

import standard_types

import standard
#include standard_abortivetransaction
import standard_address
import standard_arraystreambuffer
import standard_assert
import standard_atomic
import standard_boolean
import standard_byte
import standard_character
import standard_clocalesentry
import standard_condition
#include standard_constructionerror
import standard_cstring
import standard_definealloc
import standard_defineexception
import standard_definehandle
#include standard_dimensionerror
#include standard_dimensionmismatch
#include standard_dividebyzero
#include standard_domainerror
#include standard_dump
import standard_errorhandler
import standard_extcharacter
import standard_extstring
import standard_failure
import standard_guid
import standard_handle
import standard_handlerstatus
#include standard_immutableobject
import standard_integer
#import standard_istream
import standard_jmpbuf
#include standard_licenseerror
#include standard_licensenotfound
import standard_macro
import standard_math
import standard_mmgropt
import standard_mmgrraw
import standard_mmgrroot
import standard_mmgrtbballoc
#include standard_multiplydefined
import standard_mutex
#include standard_negativevalue
#include standard_nomoreobject
#include standard_nosuchobject
#include standard_notimplemented
#include standard_nullobject
#include standard_nullvalue
#include standard_numericerror
#import standard_ostream
#include standard_outofmemory
#include standard_outofrange
#include standard_overflow
#import standard_pbyte
import standard_pcharacter
#import standard_perrorhandler
import standard_persistent
#import standard_pextcharacter
import standard_primitivetypes
#include standard_programerror
#include standard_rangeerror
import standard_readbuffer
import standard_readlinebuffer
import standard_real
import standard_shortreal
import standard_size
#import standard_sstream
import standard_std
#import standard_stream
import standard_threadid
import standard_time
#include standard_toomanyusers
import standard_transient
import standard_type
import standard_typedef
#include standard_typemismatch
#include standard_underflow
import standard_uuid
import standard_version
#include standard_warningdisablefunctioncast
#include standard_warningsdisable
#include standard_warningsrestore

export standard_types
export standard
export standard_address
export standard_arraystreambuffer
export standard_assert
export standard_atomic
export standard_boolean
export standard_byte
export standard_character
export standard_clocalesentry
export standard_condition
export standard_cstring
export standard_definealloc
export standard_defineexception
export standard_definehandle
export standard_errorhandler
export standard_extcharacter
export standard_extstring
export standard_failure
export standard_guid
export standard_handle
export standard_handlerstatus
export standard_integer
#export standard_istream
export standard_jmpbuf
export standard_macro
export standard_math
export standard_mmgropt
export standard_mmgrraw
export standard_mmgrroot
export standard_mmgrtbballoc
export standard_mutex
#export standard_ostream
#export standard_pbyte
export standard_pcharacter
#export standard_perrorhandler
export standard_persistent
#export standard_pextcharacter
export standard_primitivetypes
export standard_readbuffer
export standard_readlinebuffer
export standard_real
export standard_shortreal
export standard_size
#export standard_sstream
export standard_std
#export standard_stream
export standard_threadid
export standard_time
export standard_transient
export standard_type
export standard_typedef
export standard_uuid
export standard_version
