{.passC:"-I/usr/include/opencascade/" .}
{.experimental: "codeReordering".}
{.experimental: "callOperator".}

include Graphic3d_AlphaMode
include Graphic3d_ArrayFlags
include Graphic3d_ArrayOfPoints
include Graphic3d_ArrayOfPolygons
include Graphic3d_ArrayOfPolylines
include Graphic3d_ArrayOfPrimitives
include Graphic3d_ArrayOfQuadrangleStrips
include Graphic3d_ArrayOfQuadrangles
include Graphic3d_ArrayOfSegments
include Graphic3d_ArrayOfTriangleFans
include Graphic3d_ArrayOfTriangleStrips
include Graphic3d_ArrayOfTriangles
include Graphic3d_AspectFillArea3d
include Graphic3d_AspectLine3d
include Graphic3d_AspectMarker3d
include Graphic3d_AspectText3d
include Graphic3d_Aspects
include Graphic3d_AttribBuffer
include Graphic3d_BSDF
include Graphic3d_BndBox3d
include Graphic3d_BndBox4d
include Graphic3d_BndBox4f
include Graphic3d_BoundBuffer
include Graphic3d_Buffer
include Graphic3d_BufferRange
include Graphic3d_BufferType
include Graphic3d_BvhCStructureSet
include Graphic3d_BvhCStructureSetTrsfPers
include Graphic3d_CLight
include Graphic3d_CStructure
include Graphic3d_CTexture
include Graphic3d_CView
include Graphic3d_Camera
include Graphic3d_CameraTile
include Graphic3d_CappingFlags
include Graphic3d_ClipPlane
include Graphic3d_CubeMap
include Graphic3d_CubeMapOrder
include Graphic3d_CubeMapPacked
include Graphic3d_CubeMapSeparate
include Graphic3d_CubeMapSide
include Graphic3d_CullingTool
include Graphic3d_DataStructureManager
include Graphic3d_DiagnosticInfo
include Graphic3d_FrameStats
include Graphic3d_FrameStatsCounter
include Graphic3d_FrameStatsData
include Graphic3d_FrameStatsTimer
include Graphic3d_GraduatedTrihedron
include Graphic3d_GraphicDriver
include Graphic3d_Group
include Graphic3d_GroupAspect
include Graphic3d_GroupDefinitionError
include Graphic3d_HatchStyle
include Graphic3d_HighlightStyle
include Graphic3d_HorizontalTextAlignment
include Graphic3d_IndexBuffer
include Graphic3d_Layer
include Graphic3d_LevelOfTextureAnisotropy
include Graphic3d_LightSet
include Graphic3d_MapIteratorOfMapOfStructure
include Graphic3d_MapOfAspectsToAspects
include Graphic3d_MapOfObject
include Graphic3d_MapOfStructure
include Graphic3d_MapOfZLayerSettings
include Graphic3d_MarkerImage
include Graphic3d_Mat4
include Graphic3d_Mat4d
include Graphic3d_MaterialAspect
include Graphic3d_MaterialDefinitionError
include Graphic3d_MediaTexture
include Graphic3d_MediaTextureSet
include Graphic3d_MutableIndexBuffer
include Graphic3d_NMapOfTransient
include Graphic3d_NameOfMaterial
include Graphic3d_NameOfTexture1D
include Graphic3d_NameOfTexture2D
include Graphic3d_NameOfTextureEnv
include Graphic3d_NameOfTexturePlane
include Graphic3d_PBRMaterial
include Graphic3d_PolygonOffset
include Graphic3d_PresentationAttributes
include Graphic3d_PriorityDefinitionError
include Graphic3d_RenderTransparentMethod
include Graphic3d_RenderingMode
include Graphic3d_RenderingParams
include Graphic3d_SequenceOfGroup
include Graphic3d_SequenceOfHClipPlane
include Graphic3d_SequenceOfStructure
include Graphic3d_ShaderAttribute
include Graphic3d_ShaderObject
include Graphic3d_ShaderProgram
include Graphic3d_ShaderVariable
include Graphic3d_StereoMode
include Graphic3d_Structure
include Graphic3d_StructureDefinitionError
include Graphic3d_StructureManager
include Graphic3d_Text
include Graphic3d_TextPath
include Graphic3d_Texture1D
include Graphic3d_Texture1Dmanual
include Graphic3d_Texture1Dsegment
include Graphic3d_Texture2D
include Graphic3d_Texture2Dmanual
include Graphic3d_Texture2Dplane
include Graphic3d_TextureEnv
include Graphic3d_TextureMap
include Graphic3d_TextureParams
include Graphic3d_TextureRoot
include Graphic3d_TextureSet
include Graphic3d_TextureSetBits
include Graphic3d_TextureUnit
include Graphic3d_ToneMappingMethod
include Graphic3d_TransModeFlags
include Graphic3d_TransformError
include Graphic3d_TransformPers
include Graphic3d_TransformUtils
include Graphic3d_TypeOfAnswer
include Graphic3d_TypeOfBackfacingModel
include Graphic3d_TypeOfBackground
include Graphic3d_TypeOfComposition
include Graphic3d_TypeOfConnection
include Graphic3d_TypeOfLightSource
include Graphic3d_TypeOfLimit
include Graphic3d_TypeOfMaterial
include Graphic3d_TypeOfPrimitiveArray
include Graphic3d_TypeOfReflection
include Graphic3d_TypeOfShaderObject
include Graphic3d_TypeOfShadingModel
include Graphic3d_TypeOfStructure
include Graphic3d_TypeOfTexture
include Graphic3d_TypeOfTextureFilter
include Graphic3d_TypeOfTextureMode
include Graphic3d_TypeOfVisualization
include Graphic3d_Vec
include Graphic3d_Vec2
include Graphic3d_Vec3
include Graphic3d_Vec4
include Graphic3d_Vertex
include Graphic3d_VerticalTextAlignment
include Graphic3d_ViewAffinity
include Graphic3d_WorldViewProjState
include Graphic3d_ZLayerId
include Graphic3d_ZLayerSettings


























