{.passL:"-lTKMath".}
{.passC:"-I/usr/include/opencascade/" .}
{.experimental: "codeReordering".}

import selectmgr
import selectmgr_andfilter
import selectmgr_andorfilter
import selectmgr_basefrustum
import selectmgr_bvhthreadpool
import selectmgr_compositionfilter
import selectmgr_entityowner
import selectmgr_filter
import selectmgr_filtertype
import selectmgr_frustum
import selectmgr_frustumbuilder
import selectmgr_indexeddatamapofownercriterion
import selectmgr_indexedmapofowner
import selectmgr_listiteratoroflistoffilter
import selectmgr_listoffilter
import selectmgr_orfilter
import selectmgr_pickingstrategy
import selectmgr_rectangularfrustum
import selectmgr_selectableobject
import selectmgr_selectableobjectset
import selectmgr_selectingvolumemanager
import selectmgr_selection
import selectmgr_selectionimagefiller
import selectmgr_selectionmanager
import selectmgr_sensitiveentity
import selectmgr_sensitiveentityset
import selectmgr_sequenceoffilter
import selectmgr_sequenceofowner
import selectmgr_sequenceofselection
import selectmgr_sortcriterion
import selectmgr_stateofselection
import selectmgr_tolerancemap
import selectmgr_triangularfrustum
import selectmgr_triangularfrustumset
import selectmgr_typeofbvhupdate
import selectmgr_typeofdepthtolerance
import selectmgr_typeofupdate
import selectmgr_vectortypes
import selectmgr_viewcliprange
import selectmgr_viewerselector
import selectmgr_viewerselector3d

export selectmgr, selectmgr_andfilter, selectmgr_andorfilter, selectmgr_basefrustum, selectmgr_bvhthreadpool, selectmgr_compositionfilter, selectmgr_entityowner, selectmgr_filter, selectmgr_filtertype, selectmgr_frustum, selectmgr_frustumbuilder, selectmgr_indexeddatamapofownercriterion, selectmgr_indexedmapofowner, selectmgr_listiteratoroflistoffilter, selectmgr_listoffilter, selectmgr_orfilter, selectmgr_pickingstrategy, selectmgr_rectangularfrustum, selectmgr_selectableobject, selectmgr_selectableobjectset, selectmgr_selectingvolumemanager, selectmgr_selection, selectmgr_selectionimagefiller, selectmgr_selectionmanager, selectmgr_sensitiveentity, selectmgr_sensitiveentityset, selectmgr_sequenceoffilter, selectmgr_sequenceofowner, selectmgr_sequenceofselection, selectmgr_sortcriterion, selectmgr_stateofselection, selectmgr_tolerancemap, selectmgr_triangularfrustum, selectmgr_triangularfrustumset, selectmgr_typeofbvhupdate, selectmgr_typeofdepthtolerance, selectmgr_typeofupdate, selectmgr_vectortypes, selectmgr_viewcliprange, selectmgr_viewerselector, selectmgr_viewerselector3d
