{.passC:"-I/usr/include/opencascade/" .}
{.experimental: "codeReordering".}
{.experimental: "callOperator".}

include TColStd_Array1OfAsciiString
include TColStd_Array1OfBoolean
include TColStd_Array1OfByte
include TColStd_Array1OfCharacter
include TColStd_Array1OfExtendedString
include TColStd_Array1OfInteger
include TColStd_Array1OfListOfInteger
include TColStd_Array1OfReal
include TColStd_Array1OfTransient
include TColStd_Array2OfBoolean
include TColStd_Array2OfCharacter
include TColStd_Array2OfInteger
include TColStd_Array2OfReal
include TColStd_Array2OfTransient
include TColStd_DataMapIteratorOfDataMapOfAsciiStringInteger
include TColStd_DataMapIteratorOfDataMapOfIntegerInteger
include TColStd_DataMapIteratorOfDataMapOfIntegerListOfInteger
include TColStd_DataMapIteratorOfDataMapOfIntegerReal
include TColStd_DataMapIteratorOfDataMapOfIntegerTransient
include TColStd_DataMapIteratorOfDataMapOfStringInteger
include TColStd_DataMapIteratorOfDataMapOfTransientTransient
include TColStd_DataMapOfAsciiStringInteger
include TColStd_DataMapOfIntegerInteger
include TColStd_DataMapOfIntegerListOfInteger
include TColStd_DataMapOfIntegerReal
include TColStd_DataMapOfIntegerTransient
include TColStd_DataMapOfStringInteger
include TColStd_DataMapOfTransientTransient
include TColStd_HArray1OfAsciiString
include TColStd_HArray1OfBoolean
include TColStd_HArray1OfByte
include TColStd_HArray1OfCharacter
include TColStd_HArray1OfExtendedString
include TColStd_HArray1OfInteger
include TColStd_HArray1OfListOfInteger
include TColStd_HArray1OfReal
include TColStd_HArray1OfTransient
include TColStd_HArray2OfBoolean
include TColStd_HArray2OfCharacter
include TColStd_HArray2OfInteger
include TColStd_HArray2OfReal
include TColStd_HArray2OfTransient
include TColStd_HPackedMapOfInteger
include TColStd_HSequenceOfAsciiString
include TColStd_HSequenceOfExtendedString
include TColStd_HSequenceOfHAsciiString
include TColStd_HSequenceOfHExtendedString
include TColStd_HSequenceOfInteger
include TColStd_HSequenceOfReal
include TColStd_HSequenceOfTransient
include TColStd_IndexedDataMapOfStringString
include TColStd_IndexedDataMapOfTransientTransient
include TColStd_IndexedMapOfInteger
include TColStd_IndexedMapOfReal
include TColStd_IndexedMapOfTransient
include TColStd_ListIteratorOfListOfAsciiString
include TColStd_ListIteratorOfListOfInteger
include TColStd_ListIteratorOfListOfReal
include TColStd_ListIteratorOfListOfTransient
include TColStd_ListOfAsciiString
include TColStd_ListOfInteger
include TColStd_ListOfReal
include TColStd_ListOfTransient
include TColStd_MapIntegerHasher
include TColStd_MapIteratorOfMapOfAsciiString
include TColStd_MapIteratorOfMapOfInteger
include TColStd_MapIteratorOfMapOfReal
include TColStd_MapIteratorOfMapOfTransient
include TColStd_MapIteratorOfPackedMapOfInteger
include TColStd_MapOfAsciiString
include TColStd_MapOfInteger
include TColStd_MapOfReal
include TColStd_MapOfTransient
include TColStd_MapRealHasher
include TColStd_MapTransientHasher
include TColStd_PackedMapOfInteger
include TColStd_SequenceOfAddress
include TColStd_SequenceOfAsciiString
include TColStd_SequenceOfBoolean
include TColStd_SequenceOfExtendedString
include TColStd_SequenceOfHAsciiString
include TColStd_SequenceOfHExtendedString
include TColStd_SequenceOfInteger
include TColStd_SequenceOfReal
include TColStd_SequenceOfTransient


























