{.passL:"-lTKernel".}
{.passC:"-I/usr/include/opencascade/" .}

import ncollection/ncollection_types

import ncollection/ncollection_accallocator
import ncollection/ncollection_alignedallocator
import ncollection/ncollection_array1
import ncollection/ncollection_array2
#import ncollection/ncollection_baseallocator
import ncollection/ncollection_baselist
import ncollection/ncollection_basemap
import ncollection/ncollection_basesequence
import ncollection/ncollection_basevector
import ncollection/ncollection_buffer
import ncollection/ncollection_cellfilter
import ncollection/ncollection_datamap
import ncollection/ncollection_defaulthasher
import ncollection/ncollection_definealloc
#include ncollection/ncollection_definearray1
#include ncollection/ncollection_definearray2
#include ncollection/ncollection_definedatamap
#include ncollection/ncollection_definedoublemap
import ncollection/ncollection_defineharray1
import ncollection/ncollection_defineharray2
import ncollection/ncollection_definehsequence
#include ncollection/ncollection_defineindexeddatamap
#include ncollection/ncollection_defineindexedmap
#include ncollection/ncollection_definelist
#include ncollection/ncollection_definemap
#include ncollection/ncollection_definesequence
#include ncollection/ncollection_definevector
import ncollection/ncollection_doublemap
import ncollection/ncollection_ebtree
import ncollection/ncollection_handle
import ncollection/ncollection_harray1
import ncollection/ncollection_harray2
import ncollection/ncollection_heapallocator
import ncollection/ncollection_hsequence
import ncollection/ncollection_incallocator
import ncollection/ncollection_indexeddatamap
import ncollection/ncollection_indexedmap
import ncollection/ncollection_lerp
import ncollection/ncollection_list
import ncollection/ncollection_listnode
import ncollection/ncollection_localarray
import ncollection/ncollection_map
import ncollection/ncollection_mat4
import ncollection/ncollection_sequence
import ncollection/ncollection_shared
import ncollection/ncollection_sparsearray
import ncollection/ncollection_sparsearraybase
import ncollection/ncollection_stdallocator
import ncollection/ncollection_stliterator
import ncollection/ncollection_string
import ncollection/ncollection_tlistiterator
import ncollection/ncollection_tlistnode
import ncollection/ncollection_typedef
import ncollection/ncollection_ubtree
import ncollection/ncollection_ubtreefiller
import ncollection/ncollection_utfiterator
import ncollection/ncollection_utfstring
import ncollection/ncollection_vec2
import ncollection/ncollection_vec3
import ncollection/ncollection_vec4
import ncollection/ncollection_vector
import ncollection/ncollection_winheapallocator



export ncollection_types
export ncollection_accallocator, ncollection_alignedallocator, ncollection_array1
export ncollection_array2,  ncollection_baselist # ncollection_baseallocator,
export ncollection_basemap, ncollection_basesequence, ncollection_basevector
export ncollection_buffer, ncollection_cellfilter, ncollection_datamap
export ncollection_defaulthasher, ncollection_definealloc, ncollection_defineharray1
export ncollection_defineharray2, ncollection_definehsequence, ncollection_doublemap
export ncollection_ebtree, ncollection_handle, ncollection_harray1, ncollection_harray2
export ncollection_heapallocator, ncollection_hsequence, ncollection_incallocator
export ncollection_indexeddatamap, ncollection_indexedmap, ncollection_lerp
export ncollection_list, ncollection_listnode, ncollection_localarray, ncollection_map
export ncollection_mat4, ncollection_sequence, ncollection_shared, ncollection_sparsearray
export ncollection_sparsearraybase, ncollection_stdallocator, ncollection_stliterator
export ncollection_string, ncollection_tlistiterator, ncollection_tlistnode
export ncollection_typedef, ncollection_ubtree, ncollection_ubtreefiller
export ncollection_utfiterator, ncollection_utfstring, ncollection_vec2
export ncollection_vec3, ncollection_vec4, ncollection_vector
export ncollection_winheapallocator
