{.passL:"-lTKMath".}
{.passC:"-I/usr/include/opencascade/" .}
{.experimental: "codeReordering".}

import bopalgo_algo
import bopalgo_argumentanalyzer
import bopalgo_bop
import bopalgo_builder
import bopalgo_builderarea
import bopalgo_builderface
import bopalgo_buildershape
import bopalgo_buildersolid
import bopalgo_cellsbuilder
import bopalgo_checkersi
import bopalgo_checkresult
import bopalgo_checkstatus
import bopalgo_glueenum
import bopalgo_listofcheckresult
import bopalgo_makeconnected
import bopalgo_makeperiodic
import bopalgo_makervolume
import bopalgo_operation
import bopalgo_options
import bopalgo_pargumentanalyzer
import bopalgo_pavefiller
import bopalgo_pbop
import bopalgo_pbuilder
import bopalgo_ppavefiller
import bopalgo_psection
import bopalgo_pwireedgeset
import bopalgo_removefeatures
import bopalgo_section
import bopalgo_sectionattribute
import bopalgo_shellsplitter
import bopalgo_splitter
import bopalgo_tools
import bopalgo_toolsprovider
import bopalgo_wireedgeset
import bopalgo_wiresplitter

export bopalgo_algo, bopalgo_argumentanalyzer, bopalgo_bop, bopalgo_builder, bopalgo_builderarea, bopalgo_builderface, bopalgo_buildershape, bopalgo_buildersolid, bopalgo_cellsbuilder, bopalgo_checkersi, bopalgo_checkresult, bopalgo_checkstatus, bopalgo_glueenum, bopalgo_listofcheckresult, bopalgo_makeconnected, bopalgo_makeperiodic, bopalgo_makervolume, bopalgo_operation, bopalgo_options, bopalgo_pargumentanalyzer, bopalgo_pavefiller, bopalgo_pbop, bopalgo_pbuilder, bopalgo_ppavefiller, bopalgo_psection, bopalgo_pwireedgeset, bopalgo_removefeatures, bopalgo_section, bopalgo_sectionattribute, bopalgo_shellsplitter, bopalgo_splitter, bopalgo_tools, bopalgo_toolsprovider, bopalgo_wireedgeset, bopalgo_wiresplitter
