{.passC:"-I/usr/include/opencascade/" .}
{.experimental: "codeReordering".}
{.experimental: "callOperator".}

include Geom2dInt_ExactIntersectionPointOfTheIntPCurvePCurveOfGInter
#include Geom2dInt_GInter
include Geom2dInt_Geom2dCurveTool
include Geom2dInt_IntConicCurveOfGInter
include Geom2dInt_MyImpParToolOfTheIntersectorOfTheIntConicCurveOfGInter
include Geom2dInt_PCLocFOfTheLocateExtPCOfTheProjPCurOfGInter
include Geom2dInt_TheCurveLocatorOfTheProjPCurOfGInter
include Geom2dInt_TheDistBetweenPCurvesOfTheIntPCurvePCurveOfGInter
#include Geom2dInt_TheIntConicCurveOfGInter
include Geom2dInt_TheIntPCurvePCurveOfGInter
include Geom2dInt_TheIntersectorOfTheIntConicCurveOfGInter
include Geom2dInt_TheLocateExtPCOfTheProjPCurOfGInter
#include Geom2dInt_ThePolygon2dOfTheIntPCurvePCurveOfGInter
include Geom2dInt_TheProjPCurOfGInter
