{.passC:"-I/usr/include/opencascade/" .}
{.experimental: "codeReordering".}
{.experimental: "callOperator".}

include Interface_Array1OfFileParameter
include Interface_Array1OfHAsciiString
include Interface_BitMap
include Interface_Category
include Interface_Check
include Interface_CheckFailure
include Interface_CheckIterator
include Interface_CheckStatus
include Interface_CheckTool
include Interface_CopyControl
include Interface_CopyMap
include Interface_CopyTool
include Interface_DataMapIteratorOfDataMapOfTransientInteger
include Interface_DataMapOfTransientInteger
include Interface_DataState
include Interface_EntityCluster
include Interface_EntityIterator
include Interface_EntityList
include Interface_FileParameter
include Interface_FileReaderData
include Interface_FileReaderTool
include Interface_FloatWriter
include Interface_GTool
include Interface_GeneralLib
include Interface_GeneralModule
include Interface_GlobalNodeOfGeneralLib
include Interface_GlobalNodeOfReaderLib
include Interface_Graph
include Interface_GraphContent
include Interface_HArray1OfHAsciiString
include Interface_HGraph
include Interface_HSequenceOfCheck
include Interface_IndexedMapOfAsciiString
include Interface_IntList
include Interface_IntVal
include Interface_InterfaceError
include Interface_InterfaceMismatch
include Interface_InterfaceModel
include Interface_LineBuffer
include Interface_MSG
include Interface_Macros
include Interface_MapAsciiStringHasher
include Interface_NodeOfGeneralLib
include Interface_NodeOfReaderLib
include Interface_ParamList
include Interface_ParamSet
include Interface_ParamType
include Interface_Protocol
include Interface_ReaderLib
include Interface_ReaderModule
include Interface_ReportEntity
include Interface_STAT
include Interface_SequenceOfCheck
include Interface_ShareFlags
include Interface_ShareTool
include Interface_SignLabel
include Interface_SignType
include Interface_Static
include Interface_StaticSatisfies
include Interface_Statics
include Interface_Translates
include Interface_TypedValue
include Interface_UndefinedContent
include Interface_ValueInterpret
include Interface_ValueSatisfies
include Interface_VectorOfFileParameter
include Interface_Version


























