{.passL:"-lTKTopAlgo".}
{.passC:"-I/usr/include/opencascade/" .}


import brepbuilderapi_types
import brepbuilderapi
import brepbuilderapi_bndboxtreeselector
import brepbuilderapi_cellfilter
import brepbuilderapi_collect
import brepbuilderapi_command
import brepbuilderapi_copy
import brepbuilderapi_edgeerror
import brepbuilderapi_faceerror
import brepbuilderapi_fastsewing
import brepbuilderapi_findplane
import brepbuilderapi_gtransform
import brepbuilderapi_makeedge
import brepbuilderapi_makeedge2d
import brepbuilderapi_makeface
import brepbuilderapi_makepolygon
import brepbuilderapi_makeshape
import brepbuilderapi_makeshell
import brepbuilderapi_makesolid
import brepbuilderapi_makevertex
import brepbuilderapi_makewire
import brepbuilderapi_modifyshape
import brepbuilderapi_nurbsconvert
import brepbuilderapi_pipeerror
import brepbuilderapi_sewing
import brepbuilderapi_shapemodification
import brepbuilderapi_shellerror
import brepbuilderapi_transform
import brepbuilderapi_transitionmode
import brepbuilderapi_vertexinspector
import brepbuilderapi_wireerror

export brepbuilderapi_types, brepbuilderapi, brepbuilderapi_bndboxtreeselector, brepbuilderapi_cellfilter, brepbuilderapi_collect, brepbuilderapi_command, brepbuilderapi_copy, brepbuilderapi_edgeerror, brepbuilderapi_faceerror, brepbuilderapi_fastsewing, brepbuilderapi_findplane, brepbuilderapi_gtransform, brepbuilderapi_makeedge, brepbuilderapi_makeedge2d, brepbuilderapi_makeface, brepbuilderapi_makepolygon, brepbuilderapi_makeshape, brepbuilderapi_makeshell, brepbuilderapi_makesolid, brepbuilderapi_makevertex, brepbuilderapi_makewire, brepbuilderapi_modifyshape, brepbuilderapi_nurbsconvert, brepbuilderapi_pipeerror, brepbuilderapi_sewing, brepbuilderapi_shapemodification, brepbuilderapi_shellerror, brepbuilderapi_transform, brepbuilderapi_transitionmode, brepbuilderapi_vertexinspector, brepbuilderapi_wireerror
