{.passL:"-lTKGeomAlgo".}
{.passC:"-I/usr/include/opencascade/" .}

import intsurf
import intsurf_allocator
import intsurf_couple
import intsurf_interiorpoint
import intsurf_interiorpointtool
import intsurf_lineon2s
import intsurf_listiteratoroflistofpnton2s
import intsurf_listofpnton2s
import intsurf_pathpoint
import intsurf_pathpointtool
import intsurf_pnton2s
import intsurf_quadric
import intsurf_quadrictool
import intsurf_sequenceofcouple
import intsurf_sequenceofinteriorpoint
import intsurf_sequenceofpathpoint
import intsurf_sequenceofpnton2s
import intsurf_situation
import intsurf_transition
import intsurf_typetrans

export intsurf, intsurf_allocator, intsurf_couple, intsurf_interiorpoint, intsurf_interiorpointtool, intsurf_lineon2s, intsurf_listiteratoroflistofpnton2s, intsurf_listofpnton2s, intsurf_pathpoint, intsurf_pathpointtool, intsurf_pnton2s, intsurf_quadric, intsurf_quadrictool, intsurf_sequenceofcouple, intsurf_sequenceofinteriorpoint, intsurf_sequenceofpathpoint, intsurf_sequenceofpnton2s, intsurf_situation, intsurf_transition, intsurf_typetrans
