{.passC:"-I/usr/include/opencascade/" .}
{.experimental: "codeReordering".}
{.experimental: "callOperator".}

include IGESDimen
include IGESDimen_AngularDimension
include IGESDimen_Array1OfGeneralNote
include IGESDimen_Array1OfLeaderArrow
include IGESDimen_BasicDimension
include IGESDimen_CenterLine
include IGESDimen_CurveDimension
include IGESDimen_DiameterDimension
include IGESDimen_DimensionDisplayData
include IGESDimen_DimensionTolerance
include IGESDimen_DimensionUnits
include IGESDimen_DimensionedGeometry
include IGESDimen_FlagNote
include IGESDimen_GeneralLabel
include IGESDimen_GeneralModule
include IGESDimen_GeneralNote
include IGESDimen_GeneralSymbol
include IGESDimen_HArray1OfGeneralNote
include IGESDimen_HArray1OfLeaderArrow
include IGESDimen_LeaderArrow
include IGESDimen_LinearDimension
include IGESDimen_NewDimensionedGeometry
include IGESDimen_NewGeneralNote
include IGESDimen_OrdinateDimension
include IGESDimen_PointDimension
include IGESDimen_Protocol
include IGESDimen_RadiusDimension
include IGESDimen_ReadWriteModule
include IGESDimen_Section
include IGESDimen_SectionedArea
include IGESDimen_SpecificModule
include IGESDimen_ToolAngularDimension
include IGESDimen_ToolBasicDimension
include IGESDimen_ToolCenterLine
include IGESDimen_ToolCurveDimension
include IGESDimen_ToolDiameterDimension
include IGESDimen_ToolDimensionDisplayData
include IGESDimen_ToolDimensionTolerance
include IGESDimen_ToolDimensionUnits
include IGESDimen_ToolDimensionedGeometry
include IGESDimen_ToolFlagNote
include IGESDimen_ToolGeneralLabel
include IGESDimen_ToolGeneralNote
include IGESDimen_ToolGeneralSymbol
include IGESDimen_ToolLeaderArrow
include IGESDimen_ToolLinearDimension
include IGESDimen_ToolNewDimensionedGeometry
include IGESDimen_ToolNewGeneralNote
include IGESDimen_ToolOrdinateDimension
include IGESDimen_ToolPointDimension
include IGESDimen_ToolRadiusDimension
include IGESDimen_ToolSection
include IGESDimen_ToolSectionedArea
include IGESDimen_ToolWitnessLine
include IGESDimen_WitnessLine


























