{.passL:"-lTKBRep".}
{.passC:"-I/usr/include/opencascade/" .}

import brep_types
import brep_builder
import brep_curve3d
import brep_curveon2surfaces
import brep_curveonclosedsurface
import brep_curveonsurface
import brep_curverepresentation
import brep_gcurve
import brep_listiteratoroflistofcurverepresentation
import brep_listiteratoroflistofpointrepresentation
import brep_listofcurverepresentation
import brep_listofpointrepresentation
import brep_pointoncurve
import brep_pointoncurveonsurface
import brep_pointonsurface
import brep_pointrepresentation
import brep_pointsonsurface
import brep_polygon3d
import brep_polygononclosedsurface
import brep_polygononclosedtriangulation
import brep_polygononsurface
import brep_polygonontriangulation
import brep_tedge
import brep_tface
import brep_tool
import brep_tvertex

export brep_types, brep_builder, brep_curve3d, brep_curveon2surfaces, brep_curveonclosedsurface, brep_curveonsurface, brep_curverepresentation, brep_gcurve, brep_listiteratoroflistofcurverepresentation, brep_listiteratoroflistofpointrepresentation, brep_listofcurverepresentation, brep_listofpointrepresentation, brep_pointoncurve, brep_pointoncurveonsurface, brep_pointonsurface, brep_pointrepresentation, brep_pointsonsurface, brep_polygon3d, brep_polygononclosedsurface, brep_polygononclosedtriangulation, brep_polygononsurface, brep_polygonontriangulation, brep_tedge, brep_tface, brep_tool, brep_tvertex
