{.passL:"-lTKG3d".}
{.passC:"-I/usr/include/opencascade/" .}

import tcolgeom_array1ofbeziercurve
import tcolgeom_array1ofbsplinecurve
import tcolgeom_array1ofcurve
import tcolgeom_array1ofsurface
import tcolgeom_array2ofbeziersurface
import tcolgeom_array2ofsurface
import tcolgeom_harray1ofbeziercurve
import tcolgeom_harray1ofbsplinecurve
import tcolgeom_harray1ofcurve
import tcolgeom_harray1ofsurface
import tcolgeom_harray2ofsurface
import tcolgeom_hsequenceofboundedcurve
import tcolgeom_hsequenceofcurve
import tcolgeom_sequenceofboundedcurve
import tcolgeom_sequenceofcurve
import tcolgeom_sequenceofsurface

export tcolgeom_array1ofbeziercurve, tcolgeom_array1ofbsplinecurve, tcolgeom_array1ofcurve, tcolgeom_array1ofsurface, tcolgeom_array2ofbeziersurface, tcolgeom_array2ofsurface, tcolgeom_harray1ofbeziercurve, tcolgeom_harray1ofbsplinecurve, tcolgeom_harray1ofcurve, tcolgeom_harray1ofsurface, tcolgeom_harray2ofsurface, tcolgeom_hsequenceofboundedcurve, tcolgeom_hsequenceofcurve, tcolgeom_sequenceofboundedcurve, tcolgeom_sequenceofcurve, tcolgeom_sequenceofsurface
