{.passL:"-lTKMath".}
{.passC:"-I/usr/include/opencascade/" .}
{.experimental: "codeReordering".}

import message
import message_alert
import message_alertextended
import message_algorithm
import message_attribute
import message_attributemeter
import message_attributeobject
import message_attributestream
import message_compositealerts
import message_consolecolor
import message_execstatus
import message_gravity
import message_harrayofmsg
import message_level
import message_listiteratoroflistofmsg
import message_listofalert
import message_listofmsg
import message_messenger
import message_metrictype
import message_msg
import message_msgfile
import message_printer
import message_printerostream
import message_printersystemlog
import message_printertoreport
import message_progressindicator
import message_progressrange
import message_progressscope
import message_progresssentry
import message_report
import message_sequenceofprinters
import message_status
import message_statustype

export message, message_alert, message_alertextended, message_algorithm, message_attribute, message_attributemeter, message_attributeobject, message_attributestream, message_compositealerts, message_consolecolor, message_execstatus, message_gravity, message_harrayofmsg, message_level, message_listiteratoroflistofmsg, message_listofalert, message_listofmsg, message_messenger, message_metrictype, message_msg, message_msgfile, message_printer, message_printerostream, message_printersystemlog, message_printertoreport, message_progressindicator, message_progressrange, message_progressscope, message_progresssentry, message_report, message_sequenceofprinters, message_status, message_statustype
