{.passL:"-lTKernel".}
{.passC:"-I/usr/include/opencascade/" .}
{.experimental: "codeReordering".}

when defined(windows):
  const tkernel* = "TKernel.dll"
elif defined(macosx):
  const tkernel* = "libTKernel.dylib"
else:
  const tkernel* = "libTKernel.so" 


import ncollection_accallocator
import ncollection_alignedallocator
import ncollection_array1
import ncollection_array2
import ncollection_baseallocator
import ncollection_baselist
import ncollection_basemap
import ncollection_basesequence
import ncollection_basevector
import ncollection_buffer
import ncollection_cellfilter
import ncollection_datamap
import ncollection_defaulthasher
import ncollection_definealloc
#include ncollection_definearray1
#include ncollection_definearray2
#include ncollection_definedatamap
#include ncollection_definedoublemap
import ncollection_defineharray1
import ncollection_defineharray2
import ncollection_definehsequence
#include ncollection_defineindexeddatamap
#include ncollection_defineindexedmap
#include ncollection_definelist
#include ncollection_definemap
#include ncollection_definesequence
#include ncollection_definevector
import ncollection_doublemap
import ncollection_ebtree
import ncollection_handle
import ncollection_harray1
import ncollection_harray2
import ncollection_heapallocator
import ncollection_hsequence
import ncollection_incallocator
import ncollection_indexeddatamap
import ncollection_indexedmap
import ncollection_lerp
import ncollection_list
import ncollection_listnode
import ncollection_localarray
import ncollection_map
import ncollection_mat4
import ncollection_sequence
import ncollection_shared
import ncollection_sparsearray
import ncollection_sparsearraybase
import ncollection_stdallocator
import ncollection_stliterator
import ncollection_string
import ncollection_tlistiterator
import ncollection_tlistnode
import ncollection_typedef
import ncollection_ubtree
import ncollection_ubtreefiller
import ncollection_utfiterator
import ncollection_utfstring
import ncollection_vec2
import ncollection_vec3
import ncollection_vec4
import ncollection_vector
import ncollection_winheapallocator

export ncollection_accallocator, ncollection_alignedallocator, ncollection_array1, ncollection_array2, ncollection_baseallocator, ncollection_baselist, ncollection_basemap, ncollection_basesequence, ncollection_basevector, ncollection_buffer, ncollection_cellfilter, ncollection_datamap, ncollection_defaulthasher, ncollection_definealloc, ncollection_defineharray1, ncollection_defineharray2, ncollection_definehsequence, ncollection_doublemap, ncollection_ebtree, ncollection_handle, ncollection_harray1, ncollection_harray2, ncollection_heapallocator, ncollection_hsequence, ncollection_incallocator, ncollection_indexeddatamap, ncollection_indexedmap, ncollection_lerp, ncollection_list, ncollection_listnode, ncollection_localarray, ncollection_map, ncollection_mat4, ncollection_sequence, ncollection_shared, ncollection_sparsearray, ncollection_sparsearraybase, ncollection_stdallocator, ncollection_stliterator, ncollection_string, ncollection_tlistiterator, ncollection_tlistnode, ncollection_typedef, ncollection_ubtree, ncollection_ubtreefiller, ncollection_utfiterator, ncollection_utfstring, ncollection_vec2, ncollection_vec3, ncollection_vec4, ncollection_vector, ncollection_winheapallocator
