{.passL:"-lTKV3d".}
{.passC:"-I/usr/include/opencascade/" .}


import prsdim_ais_types
import prsdim_types
import prsdim
import prsdim_angledimension
import prsdim_chamf2ddimension
import prsdim_chamf3ddimension
import prsdim_concentricrelation
import prsdim_diameterdimension
import prsdim_dimension
import prsdim_dimensionowner
import prsdim_dimensionselectionmode
import prsdim_displayspecialsymbol
import prsdim_ellipseradiusdimension
import prsdim_equaldistancerelation
import prsdim_equalradiusrelation
import prsdim_fixrelation
import prsdim_identicrelation
import prsdim_kindofdimension
import prsdim_kindofrelation
import prsdim_kindofsurface
import prsdim_lengthdimension
import prsdim_maxradiusdimension
import prsdim_midpointrelation
import prsdim_minradiusdimension
import prsdim_offsetdimension
import prsdim_parallelrelation
import prsdim_perpendicularrelation
import prsdim_radiusdimension
import prsdim_relation
import prsdim_symmetricrelation
import prsdim_tangentrelation
import prsdim_typeofangle
import prsdim_typeofanglearrowvisibility
import prsdim_typeofdist

export prsdim_ais_types
export prsdim_types
export prsdim, prsdim_angledimension, prsdim_chamf2ddimension, prsdim_chamf3ddimension, prsdim_concentricrelation, prsdim_diameterdimension, prsdim_dimension, prsdim_dimensionowner, prsdim_dimensionselectionmode, prsdim_displayspecialsymbol, prsdim_ellipseradiusdimension, prsdim_equaldistancerelation, prsdim_equalradiusrelation, prsdim_fixrelation, prsdim_identicrelation, prsdim_kindofdimension, prsdim_kindofrelation, prsdim_kindofsurface, prsdim_lengthdimension, prsdim_maxradiusdimension, prsdim_midpointrelation, prsdim_minradiusdimension, prsdim_offsetdimension, prsdim_parallelrelation, prsdim_perpendicularrelation, prsdim_radiusdimension, prsdim_relation, prsdim_symmetricrelation, prsdim_tangentrelation, prsdim_typeofangle, prsdim_typeofanglearrowvisibility, prsdim_typeofdist
