{.passC:"-I/usr/include/opencascade/" .}
{.experimental: "codeReordering".}
{.experimental: "callOperator".}

include IGESDraw
include IGESDraw_Array1OfConnectPoint
include IGESDraw_Array1OfViewKindEntity
include IGESDraw_CircArraySubfigure
include IGESDraw_ConnectPoint
include IGESDraw_Drawing
include IGESDraw_DrawingWithRotation
include IGESDraw_GeneralModule
include IGESDraw_HArray1OfConnectPoint
include IGESDraw_HArray1OfViewKindEntity
include IGESDraw_LabelDisplay
include IGESDraw_NetworkSubfigure
include IGESDraw_NetworkSubfigureDef
include IGESDraw_PerspectiveView
include IGESDraw_Planar
include IGESDraw_Protocol
include IGESDraw_ReadWriteModule
include IGESDraw_RectArraySubfigure
include IGESDraw_SegmentedViewsVisible
include IGESDraw_SpecificModule
include IGESDraw_ToolCircArraySubfigure
include IGESDraw_ToolConnectPoint
include IGESDraw_ToolDrawing
include IGESDraw_ToolDrawingWithRotation
include IGESDraw_ToolLabelDisplay
include IGESDraw_ToolNetworkSubfigure
include IGESDraw_ToolNetworkSubfigureDef
include IGESDraw_ToolPerspectiveView
include IGESDraw_ToolPlanar
include IGESDraw_ToolRectArraySubfigure
include IGESDraw_ToolSegmentedViewsVisible
include IGESDraw_ToolView
include IGESDraw_ToolViewsVisible
include IGESDraw_ToolViewsVisibleWithAttr
include IGESDraw_View
include IGESDraw_ViewsVisible
include IGESDraw_ViewsVisibleWithAttr


























