{.passC:"-I/usr/include/opencascade/" .}
{.experimental: "codeReordering".}
{.experimental: "callOperator".}

include BRepCheck
include BRepCheck_Analyzer
include BRepCheck_DataMapIteratorOfDataMapOfShapeListOfStatus
include BRepCheck_DataMapIteratorOfDataMapOfShapeResult
include BRepCheck_DataMapOfShapeListOfStatus
include BRepCheck_DataMapOfShapeResult
include BRepCheck_Edge
include BRepCheck_Face
include BRepCheck_ListIteratorOfListOfStatus
include BRepCheck_ListOfStatus
include BRepCheck_Result
include BRepCheck_Shell
include BRepCheck_Solid
include BRepCheck_Status
include BRepCheck_Vertex
include BRepCheck_Wire
