{.passL:"-lTKBRep".}
{.passC:"-I/usr/include/opencascade/".}

import breptools_gtrsfmodification
import breptools_history
import breptools_modification
import breptools_modifier
import breptools
import breptools_nurbsconvertmodification
import breptools_purgelocations
import breptools_quilt
import breptools_reshape
import breptools_shapeset
import breptools_substitution
import breptools_trsfmodification
import breptools_types
import breptools_wireexplorer


export breptools_gtrsfmodification
export breptools_history
export breptools_modification
export breptools_modifier
export breptools
export breptools_nurbsconvertmodification
export breptools_purgelocations
export breptools_quilt
export breptools_reshape
export breptools_shapeset
export breptools_substitution
export breptools_trsfmodification
export breptools_types
export breptools_wireexplorer