{.passL:"-lTKMath".}
{.passC:"-I/usr/include/opencascade/" .}
{.experimental: "codeReordering".}

import appparcurves
import appparcurves_array1ofconstraintcouple
import appparcurves_array1ofmultibspcurve
import appparcurves_array1ofmulticurve
import appparcurves_array1ofmultipoint
import appparcurves_constraint
import appparcurves_constraintcouple
import appparcurves_harray1ofconstraintcouple
import appparcurves_harray1ofmultibspcurve
import appparcurves_harray1ofmulticurve
import appparcurves_harray1ofmultipoint
import appparcurves_multibspcurve
import appparcurves_multicurve
import appparcurves_multipoint
import appparcurves_sequenceofmultibspcurve
import appparcurves_sequenceofmulticurve

export appparcurves, appparcurves_array1ofconstraintcouple, appparcurves_array1ofmultibspcurve, appparcurves_array1ofmulticurve, appparcurves_array1ofmultipoint, appparcurves_constraint, appparcurves_constraintcouple, appparcurves_harray1ofconstraintcouple, appparcurves_harray1ofmultibspcurve, appparcurves_harray1ofmulticurve, appparcurves_harray1ofmultipoint, appparcurves_multibspcurve, appparcurves_multicurve, appparcurves_multipoint, appparcurves_sequenceofmultibspcurve, appparcurves_sequenceofmulticurve
