{.passL:"-lTKMath".}
{.passC:"-I/usr/include/opencascade/" .}
{.experimental: "codeReordering".}

import gp
import gp_ax1
import gp_ax2
import gp_ax22d
import gp_ax2d
import gp_ax3
import gp_circ
import gp_circ2d
import gp_cone
import gp_cylinder
import gp_dir
import gp_dir2d
import gp_elips
import gp_elips2d
import gp_eulersequence
import gp_gtrsf
import gp_gtrsf2d
import gp_hypr
import gp_hypr2d
import gp_lin
import gp_lin2d
import gp_mat
import gp_mat2d
import gp_parab
import gp_parab2d
import gp_pln
import gp_pnt
import gp_pnt2d
import gp_quaternion
import gp_quaternionnlerp
import gp_quaternionslerp
import gp_sphere
import gp_torus
import gp_trsf
import gp_trsf2d
import gp_trsfform
import gp_vec
import gp_vec2d
import gp_vectorwithnullmagnitude
import gp_xy
import gp_xyz

import gp_types
export gp_types
export gp, gp_ax1, gp_ax2, gp_ax22d, gp_ax2d, gp_ax3, gp_circ, gp_circ2d, gp_cone, gp_cylinder, gp_dir, gp_dir2d, gp_elips, gp_elips2d, gp_eulersequence, gp_gtrsf, gp_gtrsf2d, gp_hypr, gp_hypr2d, gp_lin, gp_lin2d, gp_mat, gp_mat2d, gp_parab, gp_parab2d, gp_pln, gp_pnt, gp_pnt2d, gp_quaternion, gp_quaternionnlerp, gp_quaternionslerp, gp_sphere, gp_torus, gp_trsf, gp_trsf2d, gp_trsfform, gp_vec, gp_vec2d, gp_vectorwithnullmagnitude, gp_xy, gp_xyz
