{.passL:"-lTKMath".}
{.passC:"-I/usr/include/opencascade/" .}


import convert_circletobsplinecurve
import convert_compbeziercurves2dtobsplinecurve2d
import convert_compbeziercurvestobsplinecurve
import convert_comppolynomialtopoles
import convert_conetobsplinesurface
import convert_conictobsplinecurve
import convert_cosandsinevalfunction
import convert_cylindertobsplinesurface
import convert_elementarysurfacetobsplinesurface
import convert_ellipsetobsplinecurve
import convert_gridpolynomialtopoles
import convert_hyperbolatobsplinecurve
import convert_parabolatobsplinecurve
import convert_parameterisationtype
import convert_polynomialcosandsin
import convert_sequenceofarray1ofpoles
import convert_sequenceofarray1ofpoles2d
import convert_spheretobsplinesurface
import convert_torustobsplinesurface

export convert_circletobsplinecurve, convert_compbeziercurves2dtobsplinecurve2d, convert_compbeziercurvestobsplinecurve, convert_comppolynomialtopoles, convert_conetobsplinesurface, convert_conictobsplinecurve, convert_cosandsinevalfunction, convert_cylindertobsplinesurface, convert_elementarysurfacetobsplinesurface, convert_ellipsetobsplinecurve, convert_gridpolynomialtopoles, convert_hyperbolatobsplinecurve, convert_parabolatobsplinecurve, convert_parameterisationtype, convert_polynomialcosandsin, convert_sequenceofarray1ofpoles, convert_sequenceofarray1ofpoles2d, convert_spheretobsplinesurface, convert_torustobsplinesurface
