{.passL:"-lTKMath".}
{.passC:"-I/usr/include/opencascade/" .}
{.experimental: "codeReordering".}

include topods_alertattribute
include topods_alertwithshape
include topods_builder
include topods_compound
include topods_compsolid
include topods_edge
include topods_face
include topods_frozenshape
include topods_hshape
include topods_iterator
include topods_listiteratoroflistofshape
include topods_listofshape
include topods_lockedshape
include topods_shape
include topods_shell
include topods_solid
include topods_tcompound
include topods_tcompsolid
include topods_tedge
include topods_tface
include topods_tshape
include topods_tshell
include topods_tsolid
include topods_tvertex
include topods_twire
include topods_uncompatibleshapes
include topods_vertex
include topods_wire
