{.passL:"-lTKMath".}
{.passC:"-I/usr/include/opencascade/" .}
{.experimental: "codeReordering".}

import geom_axis1placement
import geom_axis2placement
import geom_axisplacement
import geom_beziercurve
import geom_beziersurface
import geom_boundedcurve
import geom_boundedsurface
import geom_bsplinecurve
import geom_bsplinesurface
import geom_cartesianpoint
import geom_circle
import geom_conic
import geom_conicalsurface
import geom_curve
import geom_cylindricalsurface
import geom_direction
import geom_elementarysurface
import geom_ellipse
import geom_geometry
import geom_hsequenceofbsplinesurface
import geom_hyperbola
import geom_line
import geom_offsetcurve
import geom_offsetsurface
import geom_osculatingsurface
import geom_parabola
import geom_plane
import geom_point
import geom_rectangulartrimmedsurface
import geom_sequenceofbsplinesurface
import geom_sphericalsurface
import geom_surface
import geom_surfaceoflinearextrusion
import geom_surfaceofrevolution
import geom_sweptsurface
import geom_toroidalsurface
import geom_transformation
import geom_trimmedcurve
import geom_undefinedderivative
import geom_undefinedvalue
import geom_vector
import geom_vectorwithmagnitude

export geom_axis1placement, geom_axis2placement, geom_axisplacement, geom_beziercurve, geom_beziersurface, geom_boundedcurve, geom_boundedsurface, geom_bsplinecurve, geom_bsplinesurface, geom_cartesianpoint, geom_circle, geom_conic, geom_conicalsurface, geom_curve, geom_cylindricalsurface, geom_direction, geom_elementarysurface, geom_ellipse, geom_geometry, geom_hsequenceofbsplinesurface, geom_hyperbola, geom_line, geom_offsetcurve, geom_offsetsurface, geom_osculatingsurface, geom_parabola, geom_plane, geom_point, geom_rectangulartrimmedsurface, geom_sequenceofbsplinesurface, geom_sphericalsurface, geom_surface, geom_surfaceoflinearextrusion, geom_surfaceofrevolution, geom_sweptsurface, geom_toroidalsurface, geom_transformation, geom_trimmedcurve, geom_undefinedderivative, geom_undefinedvalue, geom_vector, geom_vectorwithmagnitude
