{.passC:"-I/usr/include/opencascade/" .}
{.experimental: "codeReordering".}
{.experimental: "callOperator".}

include AppDef_Array1OfMultiPointConstraint
include AppDef_BSpGradient_BFGSOfMyBSplGradientOfBSplineCompute
include AppDef_BSpParFunctionOfMyBSplGradientOfBSplineCompute
include AppDef_BSpParLeastSquareOfMyBSplGradientOfBSplineCompute
include AppDef_BSplineCompute
include AppDef_Compute
include AppDef_Gradient_BFGSOfMyGradientOfCompute
include AppDef_Gradient_BFGSOfMyGradientbisOfBSplineCompute
include AppDef_Gradient_BFGSOfTheGradient
include AppDef_HArray1OfMultiPointConstraint
include AppDef_LinearCriteria
include AppDef_MultiLine
include AppDef_MultiPointConstraint
include AppDef_MyBSplGradientOfBSplineCompute
include AppDef_MyGradientOfCompute
include AppDef_MyGradientbisOfBSplineCompute
include AppDef_MyLineTool
include AppDef_ParFunctionOfMyGradientOfCompute
include AppDef_ParFunctionOfMyGradientbisOfBSplineCompute
include AppDef_ParFunctionOfTheGradient
include AppDef_ParLeastSquareOfMyGradientOfCompute
include AppDef_ParLeastSquareOfMyGradientbisOfBSplineCompute
include AppDef_ParLeastSquareOfTheGradient
include AppDef_ResConstraintOfMyGradientOfCompute
include AppDef_ResConstraintOfMyGradientbisOfBSplineCompute
include AppDef_ResConstraintOfTheGradient
include AppDef_SmoothCriterion
include AppDef_TheFunction
include AppDef_TheGradient
include AppDef_TheLeastSquares
include AppDef_TheResol
include AppDef_Variational


























